//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::NoteShareAccess;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "note")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub title: String,
  #[sea_orm(column_type = "VarBinary(StringLen::None)")]
  pub content: Vec<u8>,
  pub preview: String,
  pub owner: Uuid,
  pub public_access: Option<NoteShareAccess>,
  pub last_updated: DateTime,
  #[sea_orm(has_many)]
  pub note_snapshots: HasMany<super::note_snapshot::Entity>,
  #[sea_orm(has_many, via = "note_user", relation_enum = "SharedUser")]
  pub shared_users: HasMany<super::user::Entity>,
  #[sea_orm(
    belongs_to,
    from = "owner",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
