//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "note_snapshot")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub created_at: DateTime,
  pub preview: String,
  pub note_id: Uuid,
  #[sea_orm(
    belongs_to,
    from = "note_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub note: BelongsTo<super::note::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
