//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::NoteShareAccess;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "note_user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub note: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub user: Uuid,
  pub access: NoteShareAccess,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::note::Entity",
    from = "Column::Note",
    to = "super::note::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Note,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::User",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::note::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Note.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
