//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::NoteShareAccess;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "note_user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub note_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub user_id: Uuid,
  pub access: NoteShareAccess,
  #[sea_orm(
    belongs_to,
    from = "note_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub note: BelongsTo<super::note::Entity>,
  #[sea_orm(
    belongs_to,
    from = "user_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
