//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::NoteShareAccess;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "note")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub title: String,
  #[sea_orm(column_type = "VarBinary(StringLen::None)")]
  pub content: Vec<u8>,
  pub preview: String,
  pub owner: Uuid,
  pub public_access: Option<NoteShareAccess>,
  pub last_updated: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::note_snapshot::Entity")]
  NoteSnapshot,
  #[sea_orm(has_many = "super::note_user::Entity")]
  NoteUser,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::Owner",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::note_snapshot::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NoteSnapshot.def()
  }
}

impl Related<super::note_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NoteUser.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    super::note_user::Relation::User.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::note_user::Relation::Note.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
