//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "o_auth_policy")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub claim: String,
  pub default: String,
  #[sea_orm(has_many)]
  pub o_auth_policy_contents: HasMany<super::o_auth_policy_content::Entity>,
  #[sea_orm(has_many, via = "o_auth_scope_o_auth_policy")]
  pub o_auth_scopes: HasMany<super::o_auth_scope::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
