//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "o_auth_policy_content")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub index: i32,
  pub policy: Uuid,
  pub content: String,
  pub group_id: Uuid,
  #[sea_orm(
    belongs_to,
    from = "group_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub group: BelongsTo<super::group::Entity>,
  #[sea_orm(
    belongs_to,
    from = "policy",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub o_auth_policy: BelongsTo<super::o_auth_policy::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
