//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "o_auth_client_additional_redirect_uri")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub client: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub redirect_uri: String,
  #[sea_orm(
    belongs_to,
    from = "client",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub o_auth_client: BelongsTo<super::o_auth_client::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
