//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "o_auth_client")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub redirect_uri: String,
  pub client_secret: String,
  pub salt: String,
  pub confidential: bool,
  pub require_pkce: bool,
  #[sea_orm(has_many)]
  pub o_auth_client_additional_redirect_uris:
    HasMany<super::o_auth_client_additional_redirect_uri::Entity>,
  #[sea_orm(has_many, via = "o_auth_client_group")]
  pub groups: HasMany<super::group::Entity>,
  #[sea_orm(has_many, via = "o_auth_client_o_auth_scope")]
  pub o_auth_scopes: HasMany<super::o_auth_scope::Entity>,
  #[sea_orm(has_many, via = "o_auth_client_user")]
  pub users: HasMany<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
