//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "o_auth_scope")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub scope: String,
  #[sea_orm(has_many, via = "o_auth_client_o_auth_scope")]
  pub o_auth_clients: HasMany<super::o_auth_client::Entity>,
  #[sea_orm(has_many, via = "o_auth_scope_o_auth_policy")]
  pub o_auth_policies: HasMany<super::o_auth_policy::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
