//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
  Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, JsonSchema,
)]
#[serde(rename_all = "lowercase")]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "note_share_access")]
pub enum NoteShareAccess {
  #[sea_orm(string_value = "view")]
  View,
  #[sea_orm(string_value = "edit")]
  Edit,
}
