//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "permission")]
pub enum Permission {
  #[sea_orm(string_value = "group_create")]
  GroupCreate,
  #[sea_orm(string_value = "group_delete")]
  GroupDelete,
  #[sea_orm(string_value = "group_edit")]
  GroupEdit,
  #[sea_orm(string_value = "group_list")]
  GroupList,
  #[sea_orm(string_value = "o_auth_client_create")]
  OAuthClientCreate,
  #[sea_orm(string_value = "o_auth_client_delete")]
  OAuthClientDelete,
  #[sea_orm(string_value = "o_auth_client_edit")]
  OAuthClientEdit,
  #[sea_orm(string_value = "o_auth_client_list")]
  OAuthClientList,
  #[sea_orm(string_value = "user_create")]
  UserCreate,
  #[sea_orm(string_value = "user_delete")]
  UserDelete,
  #[sea_orm(string_value = "user_edit")]
  UserEdit,
  #[sea_orm(string_value = "user_list")]
  UserList,
}
