//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "session")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub application: String,
  pub operating_system: String,
  #[sea_orm(unique)]
  pub token: String,
  pub user_id: Uuid,
  pub is_app: bool,
  pub expires_at: DateTime,
  pub created_at: DateTime,
  pub last_used_at: DateTime,
  pub refreshed_at: Option<DateTime>,
  #[sea_orm(
    belongs_to,
    from = "user_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
