//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  #[sea_orm(unique)]
  pub email: String,
  pub password: String,
  pub salt: String,
  pub oidc_user: bool,
  pub totp: Option<String>,
  #[sea_orm(unique)]
  pub oidc_subject: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::apod::Entity")]
  Apod,
  #[sea_orm(has_many = "super::group_user::Entity")]
  GroupUser,
  #[sea_orm(has_many = "super::note::Entity")]
  Note,
  #[sea_orm(has_many = "super::note_user::Entity")]
  NoteUser,
  #[sea_orm(has_many = "super::o_auth_client_user::Entity")]
  OAuthClientUser,
  #[sea_orm(has_many = "super::passkey::Entity")]
  Passkey,
  #[sea_orm(has_many = "super::session::Entity")]
  Session,
  #[sea_orm(has_one = "super::user_avatar::Entity")]
  UserAvatar,
  #[sea_orm(has_one = "super::user_settings::Entity")]
  UserSettings,
}

impl Related<super::apod::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Apod.def()
  }
}

impl Related<super::group_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::GroupUser.def()
  }
}

impl Related<super::note_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NoteUser.def()
  }
}

impl Related<super::o_auth_client_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OAuthClientUser.def()
  }
}

impl Related<super::passkey::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Passkey.def()
  }
}

impl Related<super::session::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Session.def()
  }
}

impl Related<super::user_avatar::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserAvatar.def()
  }
}

impl Related<super::user_settings::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserSettings.def()
  }
}

impl Related<super::group::Entity> for Entity {
  fn to() -> RelationDef {
    super::group_user::Relation::Group.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::group_user::Relation::User.def().rev())
  }
}

impl Related<super::note::Entity> for Entity {
  fn to() -> RelationDef {
    super::note_user::Relation::Note.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::note_user::Relation::User.def().rev())
  }
}

impl Related<super::o_auth_client::Entity> for Entity {
  fn to() -> RelationDef {
    super::o_auth_client_user::Relation::OAuthClient.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::o_auth_client_user::Relation::User.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
