//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  #[sea_orm(unique)]
  pub email: String,
  pub password: String,
  pub salt: String,
  pub oidc_user: bool,
  pub totp: Option<String>,
  #[sea_orm(unique)]
  pub oidc_subject: Option<String>,
  #[sea_orm(has_many)]
  pub apods: HasMany<super::apod::Entity>,
  #[sea_orm(has_many)]
  pub passkeys: HasMany<super::passkey::Entity>,
  #[sea_orm(has_many)]
  pub sessions: HasMany<super::session::Entity>,
  #[sea_orm(has_one)]
  pub user_avatar: HasOne<super::user_avatar::Entity>,
  #[sea_orm(has_one)]
  pub user_settings: HasOne<super::user_settings::Entity>,
  #[sea_orm(has_many, via = "group_user")]
  pub groups: HasMany<super::group::Entity>,
  #[sea_orm(has_many, via = "note_user")]
  pub notes: HasMany<super::note::Entity>,
  #[sea_orm(has_many, via = "o_auth_client_user")]
  pub o_auth_clients: HasMany<super::o_auth_client::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
