json:
  flutter pub run build_runner build --delete-conflicting-outputs

json-watch:
  flutter pub run build_runner watch --delete-conflicting-outputs

chrome:
  flutter run -d chrome --web-browser-flag "--disable-web-security"