// This file is auto-generated by @hey-api/openapi-ts

import { client, wrapMswHandler } from '$mocks/msw-runtime';

import type {
  AccountSettingsData,
  AccountSettingsResponse,
  AuthConfigData,
  AuthConfigResponse,
  AuthorizeConfirmData,
  AuthorizeConfirmResponse,
  AvatarByIdData,
  AvatarByIdResponse,
  ChangePasswordData,
  ChangePasswordError,
  ChangeUserEmailData,
  ChangeUserEmailError,
  CompleteSetupData,
  CompleteSetupError,
  ConfirmEmailChangeData,
  ConfirmEmailChangeError,
  ConvertOidcUserData,
  ConvertOidcUserError,
  CreateGroupData,
  CreateGroupError,
  CreateGroupResponse,
  CreateNoteData,
  CreateNoteError,
  CreateNoteResponse,
  CreateOauthClientData,
  CreateOauthClientError,
  CreateOauthClientResponse,
  CreateOAuthPolicyData,
  CreateOAuthPolicyError,
  CreateOAuthPolicyResponse,
  CreateOAuthScopeData,
  CreateOAuthScopeError,
  CreateOAuthScopeResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse2,
  DeleteGroupData,
  DeleteGroupError,
  DeleteNoteData,
  DeleteNoteError,
  DeleteNoteSnapshotData,
  DeleteNoteSnapshotError,
  DeleteOauthClientData,
  DeleteOauthClientError,
  DeleteOAuthPolicyData,
  DeleteOAuthPolicyError,
  DeleteOAuthScopeData,
  DeleteOAuthScopeError,
  DeleteUserData,
  DeleteUserError,
  EditGroupData,
  EditGroupError,
  EditNoteData,
  EditNoteError,
  EditOauthClientData,
  EditOauthClientError,
  EditOAuthPolicyData,
  EditOAuthPolicyError,
  EditOAuthScopeData,
  EditOAuthScopeError,
  EditPasskeyNameData,
  EditPasskeyNameError,
  EditUserData,
  EditUserError,
  ExchangeAppCodeData,
  ExchangeAppCodeError,
  FinishAuthenticationData,
  FinishAuthenticationError,
  FinishRegistrationData,
  FinishRegistrationError,
  FinishSpecialAccessData,
  FinishSpecialAccessError,
  GetApodImageData,
  GetApodImageInfoData,
  GetApodImageInfoError,
  GetApodImageInfoResponse,
  GetMailSettingsData,
  GetMailSettingsResponse,
  GetNoteSnapshotContentData,
  GetOidcSettingsData,
  GetOidcSettingsResponse,
  GroupInfoData,
  GroupInfoResponse,
  InfoData,
  InfoNoteData,
  InfoNoteResponse,
  InfoNoteShareData,
  InfoNoteShareResponse,
  InfoNoteSnapshotData,
  InfoNoteSnapshotResponse,
  InfoOauthClientData,
  InfoOauthClientResponse,
  InfoOAuthPolicyData,
  InfoOAuthPolicyResponse,
  InfoOAuthScopeData,
  InfoOAuthScopeResponse,
  InfoResponse,
  InitOidcData,
  InitOidcError,
  IsSetupData,
  IsSetupResponse2,
  KeyData,
  KeyResponse,
  ListApodData,
  ListApodResponse,
  ListGroupsData,
  ListGroupsOAuthClientData,
  ListGroupsOAuthClientResponse,
  ListGroupsOAuthPolicyData,
  ListGroupsOAuthPolicyResponse,
  ListGroupsResponse,
  ListGroupsSimpleData,
  ListGroupsSimpleResponse,
  ListNotesData,
  ListNoteSnapshotsData,
  ListNoteSnapshotsResponse,
  ListNotesResponse,
  ListOauthClientsData,
  ListOauthClientsResponse,
  ListOAuthPoliciesData,
  ListOAuthPoliciesResponse,
  ListOAuthScopesData,
  ListOAuthScopesResponse,
  ListPasskeysData,
  ListPasskeysResponse,
  ListPoliciesOAuthScopeData,
  ListPoliciesOAuthScopeResponse,
  ListScopesOAuthClientData,
  ListScopesOAuthClientResponse,
  ListUsersData,
  ListUsersNoteData,
  ListUsersNoteResponse,
  ListUsersOAuthClientData,
  ListUsersOAuthClientResponse,
  ListUsersResponse,
  ListUsersSimpleData,
  ListUsersSimpleResponse,
  LogoutData,
  MailActiveData,
  MailActiveResponse2,
  NotesConfigData,
  NotesConfigResponse,
  PasswordAuthenticateData,
  PasswordAuthenticateError,
  PasswordSpecialAccessData,
  PasswordSpecialAccessError,
  RefreshTokenData,
  RegenerateSecretOauthClientData,
  RegenerateSecretOauthClientResponse,
  RemovePasskeyData,
  RemovePasskeyError,
  RequestAppCodeData,
  RequestAppCodeError,
  RequestAppCodeResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetUserAvatarData,
  ResetUserAvatarError,
  ResetUserPasswordData,
  ResetUserPasswordError,
  RestoreNoteSnapshotData,
  RestoreNoteSnapshotError,
  RetrieveAppTokenData,
  RetrieveAppTokenError,
  SaveAccountSettingsData,
  SaveAccountSettingsError,
  SaveMailSettingsData,
  SaveMailSettingsError,
  SendResetLinkData,
  SendResetLinkError,
  SetGoodApodData,
  SetGoodApodError,
  ShareNoteData,
  ShareNoteError,
  ShareNotePublicData,
  ShareNotePublicError,
  SiteUrlData,
  SiteUrlResponse2,
  StartAuthenticationData,
  StartAuthenticationResponse,
  StartEmailChangeData,
  StartEmailChangeError,
  StartRegistrationData,
  StartSpecialAccessData,
  TestMailData,
  TestTokenData,
  TotpConfirmData,
  TotpConfirmError,
  TotpFinishSetupData,
  TotpFinishSetupError,
  TotpRemoveData,
  TotpStartSetupData,
  TotpStartSetupResponse,
  TransferNoteData,
  TransferNoteError,
  UpdateAccountData,
  UpdateAccountError,
  UpdateAvatarData,
  UpdateAvatarError,
  UpdatePasswordData,
  UpdatePasswordError,
  UserInfoData,
  UserInfoResponse
} from './types.gen';

export const isSetupMswHandler = wrapMswHandler<
  IsSetupResponse2,
  never,
  IsSetupData
>('/api/setup', 'get', client.getConfig);

export const completeSetupMswHandler = wrapMswHandler<
  never,
  CompleteSetupError,
  CompleteSetupData
>('/api/setup', 'post', client.getConfig);

export const getOidcSettingsMswHandler = wrapMswHandler<
  GetOidcSettingsResponse,
  never,
  GetOidcSettingsData
>('/api/setup/oidc', 'get', client.getConfig);

export const initOidcMswHandler = wrapMswHandler<
  never,
  InitOidcError,
  InitOidcData
>('/api/setup/oidc', 'post', client.getConfig);

export const logoutMswHandler = wrapMswHandler<never, never, LogoutData>(
  '/api/auth/logout',
  'post',
  client.getConfig
);

export const finishRegistrationMswHandler = wrapMswHandler<
  never,
  FinishRegistrationError,
  FinishRegistrationData
>('/api/auth/passkey/finish_registration', 'post', client.getConfig);

export const finishAuthenticationMswHandler = wrapMswHandler<
  never,
  FinishAuthenticationError,
  FinishAuthenticationData
>(
  '/api/auth/passkey/finish_authentication/{auth_id}',
  'post',
  client.getConfig
);

export const finishSpecialAccessMswHandler = wrapMswHandler<
  never,
  FinishSpecialAccessError,
  FinishSpecialAccessData
>('/api/auth/passkey/finish_special_access', 'post', client.getConfig);

export const startRegistrationMswHandler = wrapMswHandler<
  never,
  never,
  StartRegistrationData
>('/api/auth/passkey/start_registration', 'get', client.getConfig);

export const startAuthenticationMswHandler = wrapMswHandler<
  StartAuthenticationResponse,
  never,
  StartAuthenticationData
>('/api/auth/passkey/start_authentication', 'get', client.getConfig);

export const startSpecialAccessMswHandler = wrapMswHandler<
  never,
  never,
  StartSpecialAccessData
>('/api/auth/passkey/start_special_access', 'get', client.getConfig);

export const listPasskeysMswHandler = wrapMswHandler<
  ListPasskeysResponse,
  never,
  ListPasskeysData
>('/api/auth/passkey/list', 'get', client.getConfig);

export const removePasskeyMswHandler = wrapMswHandler<
  never,
  RemovePasskeyError,
  RemovePasskeyData
>('/api/auth/passkey/remove', 'post', client.getConfig);

export const editPasskeyNameMswHandler = wrapMswHandler<
  never,
  EditPasskeyNameError,
  EditPasskeyNameData
>('/api/auth/passkey/edit_name', 'post', client.getConfig);

export const passwordAuthenticateMswHandler = wrapMswHandler<
  never,
  PasswordAuthenticateError,
  PasswordAuthenticateData
>('/api/auth/password/authenticate', 'post', client.getConfig);

export const passwordSpecialAccessMswHandler = wrapMswHandler<
  never,
  PasswordSpecialAccessError,
  PasswordSpecialAccessData
>('/api/auth/password/special_access', 'post', client.getConfig);

export const keyMswHandler = wrapMswHandler<KeyResponse, never, KeyData>(
  '/api/auth/password/key',
  'get',
  client.getConfig
);

export const changePasswordMswHandler = wrapMswHandler<
  never,
  ChangePasswordError,
  ChangePasswordData
>('/api/auth/password/change', 'post', client.getConfig);

export const totpConfirmMswHandler = wrapMswHandler<
  never,
  TotpConfirmError,
  TotpConfirmData
>('/api/auth/totp/confirm', 'post', client.getConfig);

export const totpStartSetupMswHandler = wrapMswHandler<
  TotpStartSetupResponse,
  never,
  TotpStartSetupData
>('/api/auth/totp/start_setup', 'get', client.getConfig);

export const totpFinishSetupMswHandler = wrapMswHandler<
  never,
  TotpFinishSetupError,
  TotpFinishSetupData
>('/api/auth/totp/finish_setup', 'post', client.getConfig);

export const totpRemoveMswHandler = wrapMswHandler<
  never,
  never,
  TotpRemoveData
>('/api/auth/totp/remove', 'post', client.getConfig);

export const authConfigMswHandler = wrapMswHandler<
  AuthConfigResponse,
  never,
  AuthConfigData
>('/api/auth/config', 'get', client.getConfig);

export const requestAppCodeMswHandler = wrapMswHandler<
  RequestAppCodeResponse,
  RequestAppCodeError,
  RequestAppCodeData
>('/api/auth/app/code', 'post', client.getConfig);

export const exchangeAppCodeMswHandler = wrapMswHandler<
  never,
  ExchangeAppCodeError,
  ExchangeAppCodeData
>('/api/auth/app/exchange', 'post', client.getConfig);

export const retrieveAppTokenMswHandler = wrapMswHandler<
  never,
  RetrieveAppTokenError,
  RetrieveAppTokenData
>('/api/auth/app/retrieve_token', 'post', client.getConfig);

export const testTokenMswHandler = wrapMswHandler<never, never, TestTokenData>(
  '/api/auth/test_token',
  'get',
  client.getConfig
);

export const refreshTokenMswHandler = wrapMswHandler<
  never,
  never,
  RefreshTokenData
>('/api/auth/refresh_token', 'get', client.getConfig);

export const resetUserAvatarMswHandler = wrapMswHandler<
  never,
  ResetUserAvatarError,
  ResetUserAvatarData
>('/api/user/management/avatar', 'delete', client.getConfig);

export const deleteUserMswHandler = wrapMswHandler<
  never,
  DeleteUserError,
  DeleteUserData
>('/api/user/management', 'delete', client.getConfig);

export const listUsersMswHandler = wrapMswHandler<
  ListUsersResponse,
  never,
  ListUsersData
>('/api/user/management', 'get', client.getConfig);

export const createUserMswHandler = wrapMswHandler<
  CreateUserResponse2,
  CreateUserError,
  CreateUserData
>('/api/user/management', 'post', client.getConfig);

export const editUserMswHandler = wrapMswHandler<
  never,
  EditUserError,
  EditUserData
>('/api/user/management', 'put', client.getConfig);

export const userInfoMswHandler = wrapMswHandler<
  UserInfoResponse,
  never,
  UserInfoData
>('/api/user/management/{uuid}', 'get', client.getConfig);

export const mailActiveMswHandler = wrapMswHandler<
  MailActiveResponse2,
  never,
  MailActiveData
>('/api/user/management/mail', 'get', client.getConfig);

export const listGroupsSimpleMswHandler = wrapMswHandler<
  ListGroupsSimpleResponse,
  never,
  ListGroupsSimpleData
>('/api/user/management/groups', 'get', client.getConfig);

export const resetUserPasswordMswHandler = wrapMswHandler<
  never,
  ResetUserPasswordError,
  ResetUserPasswordData
>('/api/user/management/password', 'put', client.getConfig);

export const changeUserEmailMswHandler = wrapMswHandler<
  never,
  ChangeUserEmailError,
  ChangeUserEmailData
>('/api/user/management/email', 'post', client.getConfig);

export const convertOidcUserMswHandler = wrapMswHandler<
  never,
  ConvertOidcUserError,
  ConvertOidcUserData
>('/api/user/management/convert-oidc', 'put', client.getConfig);

export const updatePasswordMswHandler = wrapMswHandler<
  never,
  UpdatePasswordError,
  UpdatePasswordData
>('/api/user/account/password', 'post', client.getConfig);

export const startEmailChangeMswHandler = wrapMswHandler<
  never,
  StartEmailChangeError,
  StartEmailChangeData
>('/api/user/account/email_change_start', 'post', client.getConfig);

export const updateAccountMswHandler = wrapMswHandler<
  never,
  UpdateAccountError,
  UpdateAccountData
>('/api/user/account/update', 'post', client.getConfig);

export const confirmEmailChangeMswHandler = wrapMswHandler<
  never,
  ConfirmEmailChangeError,
  ConfirmEmailChangeData
>('/api/user/account/email_change_confirm', 'post', client.getConfig);

export const updateAvatarMswHandler = wrapMswHandler<
  never,
  UpdateAvatarError,
  UpdateAvatarData
>('/api/user/account/avatar', 'post', client.getConfig);

export const infoMswHandler = wrapMswHandler<InfoResponse, never, InfoData>(
  '/api/user/info',
  'get',
  client.getConfig
);

export const avatarByIdMswHandler = wrapMswHandler<
  AvatarByIdResponse,
  never,
  AvatarByIdData
>('/api/user/info/avatar/{uuid}', 'get', client.getConfig);

export const getMailSettingsMswHandler = wrapMswHandler<
  GetMailSettingsResponse,
  never,
  GetMailSettingsData
>('/api/settings/mail', 'get', client.getConfig);

export const saveMailSettingsMswHandler = wrapMswHandler<
  never,
  SaveMailSettingsError,
  SaveMailSettingsData
>('/api/settings/mail', 'post', client.getConfig);

export const accountSettingsMswHandler = wrapMswHandler<
  AccountSettingsResponse,
  never,
  AccountSettingsData
>('/api/settings/account', 'get', client.getConfig);

export const saveAccountSettingsMswHandler = wrapMswHandler<
  never,
  SaveAccountSettingsError,
  SaveAccountSettingsData
>('/api/settings/account', 'post', client.getConfig);

export const sendResetLinkMswHandler = wrapMswHandler<
  never,
  SendResetLinkError,
  SendResetLinkData
>('/api/mail/reset/send', 'post', client.getConfig);

export const resetPasswordMswHandler = wrapMswHandler<
  never,
  ResetPasswordError,
  ResetPasswordData
>('/api/mail/reset/confirm', 'post', client.getConfig);

export const testMailMswHandler = wrapMswHandler<never, never, TestMailData>(
  '/api/mail/test',
  'post',
  client.getConfig
);

export const deleteGroupMswHandler = wrapMswHandler<
  never,
  DeleteGroupError,
  DeleteGroupData
>('/api/group', 'delete', client.getConfig);

export const listGroupsMswHandler = wrapMswHandler<
  ListGroupsResponse,
  never,
  ListGroupsData
>('/api/group', 'get', client.getConfig);

export const createGroupMswHandler = wrapMswHandler<
  CreateGroupResponse,
  CreateGroupError,
  CreateGroupData
>('/api/group', 'post', client.getConfig);

export const editGroupMswHandler = wrapMswHandler<
  never,
  EditGroupError,
  EditGroupData
>('/api/group', 'put', client.getConfig);

export const groupInfoMswHandler = wrapMswHandler<
  GroupInfoResponse,
  never,
  GroupInfoData
>('/api/group/{uuid}', 'get', client.getConfig);

export const listUsersSimpleMswHandler = wrapMswHandler<
  ListUsersSimpleResponse,
  never,
  ListUsersSimpleData
>('/api/group/users', 'get', client.getConfig);

export const listApodMswHandler = wrapMswHandler<
  ListApodResponse,
  never,
  ListApodData
>('/api/services/apod', 'get', client.getConfig);

export const setGoodApodMswHandler = wrapMswHandler<
  never,
  SetGoodApodError,
  SetGoodApodData
>('/api/services/apod', 'post', client.getConfig);

export const getApodImageInfoMswHandler = wrapMswHandler<
  GetApodImageInfoResponse,
  GetApodImageInfoError,
  GetApodImageInfoData
>('/api/services/apod/get_image_info', 'post', client.getConfig);

export const getApodImageMswHandler = wrapMswHandler<
  never,
  never,
  GetApodImageData
>('/api/services/apod/get_image', 'get', client.getConfig);

export const authorizeConfirmMswHandler = wrapMswHandler<
  AuthorizeConfirmResponse,
  never,
  AuthorizeConfirmData
>('/api/oauth/authorize_confirm', 'post', client.getConfig);

export const deleteOauthClientMswHandler = wrapMswHandler<
  never,
  DeleteOauthClientError,
  DeleteOauthClientData
>('/api/oauth_management/client', 'delete', client.getConfig);

export const listOauthClientsMswHandler = wrapMswHandler<
  ListOauthClientsResponse,
  never,
  ListOauthClientsData
>('/api/oauth_management/client', 'get', client.getConfig);

export const createOauthClientMswHandler = wrapMswHandler<
  CreateOauthClientResponse,
  CreateOauthClientError,
  CreateOauthClientData
>('/api/oauth_management/client', 'post', client.getConfig);

export const editOauthClientMswHandler = wrapMswHandler<
  never,
  EditOauthClientError,
  EditOauthClientData
>('/api/oauth_management/client', 'put', client.getConfig);

export const infoOauthClientMswHandler = wrapMswHandler<
  InfoOauthClientResponse,
  never,
  InfoOauthClientData
>('/api/oauth_management/client/{uuid}', 'get', client.getConfig);

export const regenerateSecretOauthClientMswHandler = wrapMswHandler<
  RegenerateSecretOauthClientResponse,
  never,
  RegenerateSecretOauthClientData
>('/api/oauth_management/client/{uuid}', 'post', client.getConfig);

export const siteUrlMswHandler = wrapMswHandler<
  SiteUrlResponse2,
  never,
  SiteUrlData
>('/api/oauth_management/client/site_url', 'get', client.getConfig);

export const listGroupsOAuthClientMswHandler = wrapMswHandler<
  ListGroupsOAuthClientResponse,
  never,
  ListGroupsOAuthClientData
>('/api/oauth_management/client/groups', 'get', client.getConfig);

export const listUsersOAuthClientMswHandler = wrapMswHandler<
  ListUsersOAuthClientResponse,
  never,
  ListUsersOAuthClientData
>('/api/oauth_management/client/users', 'get', client.getConfig);

export const listScopesOAuthClientMswHandler = wrapMswHandler<
  ListScopesOAuthClientResponse,
  never,
  ListScopesOAuthClientData
>('/api/oauth_management/client/scopes', 'get', client.getConfig);

export const deleteOAuthScopeMswHandler = wrapMswHandler<
  never,
  DeleteOAuthScopeError,
  DeleteOAuthScopeData
>('/api/oauth_management/scope', 'delete', client.getConfig);

export const listOAuthScopesMswHandler = wrapMswHandler<
  ListOAuthScopesResponse,
  never,
  ListOAuthScopesData
>('/api/oauth_management/scope', 'get', client.getConfig);

export const createOAuthScopeMswHandler = wrapMswHandler<
  CreateOAuthScopeResponse,
  CreateOAuthScopeError,
  CreateOAuthScopeData
>('/api/oauth_management/scope', 'post', client.getConfig);

export const editOAuthScopeMswHandler = wrapMswHandler<
  never,
  EditOAuthScopeError,
  EditOAuthScopeData
>('/api/oauth_management/scope', 'put', client.getConfig);

export const infoOAuthScopeMswHandler = wrapMswHandler<
  InfoOAuthScopeResponse,
  never,
  InfoOAuthScopeData
>('/api/oauth_management/scope/{uuid}', 'get', client.getConfig);

export const listPoliciesOAuthScopeMswHandler = wrapMswHandler<
  ListPoliciesOAuthScopeResponse,
  never,
  ListPoliciesOAuthScopeData
>('/api/oauth_management/scope/policies', 'get', client.getConfig);

export const deleteOAuthPolicyMswHandler = wrapMswHandler<
  never,
  DeleteOAuthPolicyError,
  DeleteOAuthPolicyData
>('/api/oauth_management/policy', 'delete', client.getConfig);

export const listOAuthPoliciesMswHandler = wrapMswHandler<
  ListOAuthPoliciesResponse,
  never,
  ListOAuthPoliciesData
>('/api/oauth_management/policy', 'get', client.getConfig);

export const createOAuthPolicyMswHandler = wrapMswHandler<
  CreateOAuthPolicyResponse,
  CreateOAuthPolicyError,
  CreateOAuthPolicyData
>('/api/oauth_management/policy', 'post', client.getConfig);

export const editOAuthPolicyMswHandler = wrapMswHandler<
  never,
  EditOAuthPolicyError,
  EditOAuthPolicyData
>('/api/oauth_management/policy', 'put', client.getConfig);

export const infoOAuthPolicyMswHandler = wrapMswHandler<
  InfoOAuthPolicyResponse,
  never,
  InfoOAuthPolicyData
>('/api/oauth_management/policy/{uuid}', 'get', client.getConfig);

export const listGroupsOAuthPolicyMswHandler = wrapMswHandler<
  ListGroupsOAuthPolicyResponse,
  never,
  ListGroupsOAuthPolicyData
>('/api/oauth_management/policy/groups', 'get', client.getConfig);

export const deleteNoteMswHandler = wrapMswHandler<
  never,
  DeleteNoteError,
  DeleteNoteData
>('/api/notes/management', 'delete', client.getConfig);

export const listNotesMswHandler = wrapMswHandler<
  ListNotesResponse,
  never,
  ListNotesData
>('/api/notes/management', 'get', client.getConfig);

export const createNoteMswHandler = wrapMswHandler<
  CreateNoteResponse,
  CreateNoteError,
  CreateNoteData
>('/api/notes/management', 'post', client.getConfig);

export const editNoteMswHandler = wrapMswHandler<
  never,
  EditNoteError,
  EditNoteData
>('/api/notes/management', 'put', client.getConfig);

export const infoNoteMswHandler = wrapMswHandler<
  InfoNoteResponse,
  never,
  InfoNoteData
>('/api/notes/management/{uuid}', 'get', client.getConfig);

export const infoNoteShareMswHandler = wrapMswHandler<
  InfoNoteShareResponse,
  never,
  InfoNoteShareData
>('/api/notes/management/{uuid}/public', 'get', client.getConfig);

export const listUsersNoteMswHandler = wrapMswHandler<
  ListUsersNoteResponse,
  never,
  ListUsersNoteData
>('/api/notes/management/users', 'get', client.getConfig);

export const shareNoteMswHandler = wrapMswHandler<
  never,
  ShareNoteError,
  ShareNoteData
>('/api/notes/management/share', 'put', client.getConfig);

export const shareNotePublicMswHandler = wrapMswHandler<
  never,
  ShareNotePublicError,
  ShareNotePublicData
>('/api/notes/management/share/public', 'put', client.getConfig);

export const transferNoteMswHandler = wrapMswHandler<
  never,
  TransferNoteError,
  TransferNoteData
>('/api/notes/management/transfer', 'put', client.getConfig);

export const notesConfigMswHandler = wrapMswHandler<
  NotesConfigResponse,
  never,
  NotesConfigData
>('/api/notes/management/config', 'get', client.getConfig);

export const listNoteSnapshotsMswHandler = wrapMswHandler<
  ListNoteSnapshotsResponse,
  never,
  ListNoteSnapshotsData
>('/api/notes/snapshots/{note_uuid}', 'get', client.getConfig);

export const deleteNoteSnapshotMswHandler = wrapMswHandler<
  never,
  DeleteNoteSnapshotError,
  DeleteNoteSnapshotData
>('/api/notes/snapshots', 'delete', client.getConfig);

export const restoreNoteSnapshotMswHandler = wrapMswHandler<
  never,
  RestoreNoteSnapshotError,
  RestoreNoteSnapshotData
>('/api/notes/snapshots/restore', 'put', client.getConfig);

export const infoNoteSnapshotMswHandler = wrapMswHandler<
  InfoNoteSnapshotResponse,
  never,
  InfoNoteSnapshotData
>('/api/notes/snapshots/{snapshot_id}/info', 'get', client.getConfig);

export const getNoteSnapshotContentMswHandler = wrapMswHandler<
  never,
  never,
  GetNoteSnapshotContentData
>('/api/notes/snapshots/{snapshot_id}/content', 'get', client.getConfig);
