// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape
} from './client';
import { client } from './client.gen';
import type {
  AccountSettingsData,
  AccountSettingsErrors,
  AccountSettingsResponses,
  AuthConfigData,
  AuthConfigErrors,
  AuthConfigResponses,
  AuthorizeConfirmData,
  AuthorizeConfirmErrors,
  AuthorizeConfirmResponses,
  AvatarByIdData,
  AvatarByIdErrors,
  AvatarByIdResponses,
  ChangePasswordData,
  ChangePasswordErrors,
  ChangeUserEmailData,
  ChangeUserEmailErrors,
  ChangeUserEmailResponses,
  CompleteSetupData,
  CompleteSetupErrors,
  ConfirmEmailChangeData,
  ConfirmEmailChangeErrors,
  ConfirmEmailChangeResponses,
  ConvertOidcUserData,
  ConvertOidcUserErrors,
  ConvertOidcUserResponses,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupResponses,
  CreateNoteData,
  CreateNoteErrors,
  CreateNoteResponses,
  CreateOauthClientData,
  CreateOauthClientErrors,
  CreateOauthClientResponses,
  CreateOAuthPolicyData,
  CreateOAuthPolicyErrors,
  CreateOAuthPolicyResponses,
  CreateOAuthScopeData,
  CreateOAuthScopeErrors,
  CreateOAuthScopeResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupResponses,
  DeleteNoteData,
  DeleteNoteErrors,
  DeleteNoteResponses,
  DeleteOauthClientData,
  DeleteOauthClientErrors,
  DeleteOauthClientResponses,
  DeleteOAuthPolicyData,
  DeleteOAuthPolicyErrors,
  DeleteOAuthPolicyResponses,
  DeleteOAuthScopeData,
  DeleteOAuthScopeErrors,
  DeleteOAuthScopeResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  EditGroupData,
  EditGroupErrors,
  EditGroupResponses,
  EditNoteData,
  EditNoteErrors,
  EditNoteResponses,
  EditOauthClientData,
  EditOauthClientErrors,
  EditOauthClientResponses,
  EditOAuthPolicyData,
  EditOAuthPolicyErrors,
  EditOAuthPolicyResponses,
  EditOAuthScopeData,
  EditOAuthScopeErrors,
  EditOAuthScopeResponses,
  EditPasskeyNameData,
  EditPasskeyNameErrors,
  EditPasskeyNameResponses,
  EditUserData,
  EditUserErrors,
  EditUserResponses,
  ExchangeAppCodeData,
  ExchangeAppCodeErrors,
  FinishAuthenticationData,
  FinishAuthenticationErrors,
  FinishRegistrationData,
  FinishRegistrationErrors,
  FinishSpecialAccessData,
  FinishSpecialAccessErrors,
  GetApodImageData,
  GetApodImageErrors,
  GetApodImageInfoData,
  GetApodImageInfoErrors,
  GetApodImageInfoResponses,
  GetMailSettingsData,
  GetMailSettingsErrors,
  GetMailSettingsResponses,
  GetOidcSettingsData,
  GetOidcSettingsErrors,
  GetOidcSettingsResponses,
  GroupInfoData,
  GroupInfoErrors,
  GroupInfoResponses,
  InfoData,
  InfoErrors,
  InfoNoteData,
  InfoNoteErrors,
  InfoNoteResponses,
  InfoOauthClientData,
  InfoOauthClientErrors,
  InfoOauthClientResponses,
  InfoOAuthPolicyData,
  InfoOAuthPolicyErrors,
  InfoOAuthPolicyResponses,
  InfoOAuthScopeData,
  InfoOAuthScopeErrors,
  InfoOAuthScopeResponses,
  InfoResponses,
  InitOidcData,
  InitOidcErrors,
  InitOidcResponses,
  IsSetupData,
  IsSetupErrors,
  IsSetupResponses,
  KeyData,
  KeyResponses,
  ListApodData,
  ListApodErrors,
  ListApodResponses,
  ListGroupsData,
  ListGroupsErrors,
  ListGroupsOAuthClientData,
  ListGroupsOAuthClientErrors,
  ListGroupsOAuthClientResponses,
  ListGroupsOAuthPolicyData,
  ListGroupsOAuthPolicyErrors,
  ListGroupsOAuthPolicyResponses,
  ListGroupsResponses,
  ListGroupsSimpleData,
  ListGroupsSimpleErrors,
  ListGroupsSimpleResponses,
  ListNotesData,
  ListNotesErrors,
  ListNotesResponses,
  ListOauthClientsData,
  ListOauthClientsErrors,
  ListOauthClientsResponses,
  ListOAuthPoliciesData,
  ListOAuthPoliciesErrors,
  ListOAuthPoliciesResponses,
  ListOAuthScopesData,
  ListOAuthScopesErrors,
  ListOAuthScopesResponses,
  ListPasskeysData,
  ListPasskeysErrors,
  ListPasskeysResponses,
  ListPoliciesOAuthScopeData,
  ListPoliciesOAuthScopeErrors,
  ListPoliciesOAuthScopeResponses,
  ListScopesOAuthClientData,
  ListScopesOAuthClientErrors,
  ListScopesOAuthClientResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersNoteData,
  ListUsersNoteErrors,
  ListUsersNoteResponses,
  ListUsersOAuthClientData,
  ListUsersOAuthClientErrors,
  ListUsersOAuthClientResponses,
  ListUsersResponses,
  ListUsersSimpleData,
  ListUsersSimpleErrors,
  ListUsersSimpleResponses,
  LogoutData,
  LogoutErrors,
  MailActiveData,
  MailActiveErrors,
  MailActiveResponses,
  PasswordAuthenticateData,
  PasswordAuthenticateErrors,
  PasswordSpecialAccessData,
  PasswordSpecialAccessErrors,
  RefreshTokenData,
  RefreshTokenErrors,
  RegenerateSecretOauthClientData,
  RegenerateSecretOauthClientErrors,
  RegenerateSecretOauthClientResponses,
  RemovePasskeyData,
  RemovePasskeyErrors,
  RemovePasskeyResponses,
  RequestAppCodeData,
  RequestAppCodeErrors,
  RequestAppCodeResponses,
  ResetPasswordData,
  ResetPasswordErrors,
  ResetPasswordResponses,
  ResetUserAvatarData,
  ResetUserAvatarErrors,
  ResetUserAvatarResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  RetrieveAppTokenData,
  RetrieveAppTokenErrors,
  SaveAccountSettingsData,
  SaveAccountSettingsErrors,
  SaveAccountSettingsResponses,
  SaveMailSettingsData,
  SaveMailSettingsErrors,
  SaveMailSettingsResponses,
  SendResetLinkData,
  SendResetLinkErrors,
  SendResetLinkResponses,
  SetGoodApodData,
  SetGoodApodErrors,
  SetGoodApodResponses,
  ShareNoteData,
  ShareNoteErrors,
  ShareNoteResponses,
  SiteUrlData,
  SiteUrlErrors,
  SiteUrlResponses,
  StartAuthenticationData,
  StartAuthenticationErrors,
  StartAuthenticationResponses,
  StartEmailChangeData,
  StartEmailChangeErrors,
  StartEmailChangeResponses,
  StartRegistrationData,
  StartRegistrationErrors,
  StartRegistrationResponses,
  StartSpecialAccessData,
  StartSpecialAccessErrors,
  StartSpecialAccessResponses,
  TestMailData,
  TestMailErrors,
  TestMailResponses,
  TestTokenData,
  TotpConfirmData,
  TotpConfirmErrors,
  TotpFinishSetupData,
  TotpFinishSetupErrors,
  TotpRemoveData,
  TotpRemoveErrors,
  TotpStartSetupData,
  TotpStartSetupErrors,
  TotpStartSetupResponses,
  UpdateAccountData,
  UpdateAccountErrors,
  UpdateAccountResponses,
  UpdateAvatarData,
  UpdateAvatarErrors,
  UpdateAvatarResponses,
  UpdatePasswordData,
  UpdatePasswordErrors,
  UpdatePasswordResponses,
  UserInfoData,
  UserInfoErrors,
  UserInfoResponses
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const isSetup = <ThrowOnError extends boolean = false>(
  options?: Options<IsSetupData, ThrowOnError>
): RequestResult<IsSetupResponses, IsSetupErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    IsSetupResponses,
    IsSetupErrors,
    ThrowOnError
  >({ url: '/api/setup', ...options });

export const completeSetup = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSetupData, ThrowOnError>
): RequestResult<unknown, CompleteSetupErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, CompleteSetupErrors, ThrowOnError>({
    url: '/api/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getOidcSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetOidcSettingsData, ThrowOnError>
): RequestResult<
  GetOidcSettingsResponses,
  GetOidcSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetOidcSettingsResponses,
    GetOidcSettingsErrors,
    ThrowOnError
  >({ url: '/api/setup/oidc', ...options });

export const initOidc = <ThrowOnError extends boolean = false>(
  options: Options<InitOidcData, ThrowOnError>
): RequestResult<InitOidcResponses, InitOidcErrors, ThrowOnError> =>
  (options.client ?? client).post<
    InitOidcResponses,
    InitOidcErrors,
    ThrowOnError
  >({
    url: '/api/setup/oidc',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
): RequestResult<unknown, LogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<unknown, LogoutErrors, ThrowOnError>({
    url: '/api/auth/logout',
    ...options
  });

export const finishRegistration = <ThrowOnError extends boolean = false>(
  options: Options<FinishRegistrationData, ThrowOnError>
): RequestResult<unknown, FinishRegistrationErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    FinishRegistrationErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/finish_registration',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const finishAuthentication = <ThrowOnError extends boolean = false>(
  options: Options<FinishAuthenticationData, ThrowOnError>
): RequestResult<unknown, FinishAuthenticationErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    FinishAuthenticationErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/finish_authentication/{auth_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const finishSpecialAccess = <ThrowOnError extends boolean = false>(
  options: Options<FinishSpecialAccessData, ThrowOnError>
): RequestResult<unknown, FinishSpecialAccessErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    FinishSpecialAccessErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/finish_special_access',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const startRegistration = <ThrowOnError extends boolean = false>(
  options?: Options<StartRegistrationData, ThrowOnError>
): RequestResult<
  StartRegistrationResponses,
  StartRegistrationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    StartRegistrationResponses,
    StartRegistrationErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/start_registration', ...options });

export const startAuthentication = <ThrowOnError extends boolean = false>(
  options?: Options<StartAuthenticationData, ThrowOnError>
): RequestResult<
  StartAuthenticationResponses,
  StartAuthenticationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    StartAuthenticationResponses,
    StartAuthenticationErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/start_authentication', ...options });

export const startSpecialAccess = <ThrowOnError extends boolean = false>(
  options?: Options<StartSpecialAccessData, ThrowOnError>
): RequestResult<
  StartSpecialAccessResponses,
  StartSpecialAccessErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    StartSpecialAccessResponses,
    StartSpecialAccessErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/start_special_access', ...options });

export const listPasskeys = <ThrowOnError extends boolean = false>(
  options?: Options<ListPasskeysData, ThrowOnError>
): RequestResult<ListPasskeysResponses, ListPasskeysErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListPasskeysResponses,
    ListPasskeysErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/list', ...options });

export const removePasskey = <ThrowOnError extends boolean = false>(
  options: Options<RemovePasskeyData, ThrowOnError>
): RequestResult<RemovePasskeyResponses, RemovePasskeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RemovePasskeyResponses,
    RemovePasskeyErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editPasskeyName = <ThrowOnError extends boolean = false>(
  options: Options<EditPasskeyNameData, ThrowOnError>
): RequestResult<
  EditPasskeyNameResponses,
  EditPasskeyNameErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    EditPasskeyNameResponses,
    EditPasskeyNameErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/edit_name',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const passwordAuthenticate = <ThrowOnError extends boolean = false>(
  options: Options<PasswordAuthenticateData, ThrowOnError>
): RequestResult<unknown, PasswordAuthenticateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    PasswordAuthenticateErrors,
    ThrowOnError
  >({
    url: '/api/auth/password/authenticate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const passwordSpecialAccess = <ThrowOnError extends boolean = false>(
  options: Options<PasswordSpecialAccessData, ThrowOnError>
): RequestResult<unknown, PasswordSpecialAccessErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    PasswordSpecialAccessErrors,
    ThrowOnError
  >({
    url: '/api/auth/password/special_access',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const key = <ThrowOnError extends boolean = false>(
  options?: Options<KeyData, ThrowOnError>
): RequestResult<KeyResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<KeyResponses, unknown, ThrowOnError>({
    url: '/api/auth/password/key',
    ...options
  });

export const changePassword = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordData, ThrowOnError>
): RequestResult<unknown, ChangePasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, ChangePasswordErrors, ThrowOnError>({
    url: '/api/auth/password/change',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const totpConfirm = <ThrowOnError extends boolean = false>(
  options: Options<TotpConfirmData, ThrowOnError>
): RequestResult<unknown, TotpConfirmErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, TotpConfirmErrors, ThrowOnError>({
    url: '/api/auth/totp/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const totpStartSetup = <ThrowOnError extends boolean = false>(
  options?: Options<TotpStartSetupData, ThrowOnError>
): RequestResult<TotpStartSetupResponses, TotpStartSetupErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    TotpStartSetupResponses,
    TotpStartSetupErrors,
    ThrowOnError
  >({ url: '/api/auth/totp/start_setup', ...options });

export const totpFinishSetup = <ThrowOnError extends boolean = false>(
  options: Options<TotpFinishSetupData, ThrowOnError>
): RequestResult<unknown, TotpFinishSetupErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, TotpFinishSetupErrors, ThrowOnError>(
    {
      url: '/api/auth/totp/finish_setup',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers
      }
    }
  );

export const totpRemove = <ThrowOnError extends boolean = false>(
  options?: Options<TotpRemoveData, ThrowOnError>
): RequestResult<unknown, TotpRemoveErrors, ThrowOnError> =>
  (options?.client ?? client).post<unknown, TotpRemoveErrors, ThrowOnError>({
    url: '/api/auth/totp/remove',
    ...options
  });

export const authConfig = <ThrowOnError extends boolean = false>(
  options?: Options<AuthConfigData, ThrowOnError>
): RequestResult<AuthConfigResponses, AuthConfigErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthConfigResponses,
    AuthConfigErrors,
    ThrowOnError
  >({ url: '/api/auth/config', ...options });

export const requestAppCode = <ThrowOnError extends boolean = false>(
  options: Options<RequestAppCodeData, ThrowOnError>
): RequestResult<RequestAppCodeResponses, RequestAppCodeErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RequestAppCodeResponses,
    RequestAppCodeErrors,
    ThrowOnError
  >({
    url: '/api/auth/app/code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const exchangeAppCode = <ThrowOnError extends boolean = false>(
  options: Options<ExchangeAppCodeData, ThrowOnError>
): RequestResult<unknown, ExchangeAppCodeErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, ExchangeAppCodeErrors, ThrowOnError>(
    {
      url: '/api/auth/app/exchange',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers
      }
    }
  );

export const retrieveAppToken = <ThrowOnError extends boolean = false>(
  options: Options<RetrieveAppTokenData, ThrowOnError>
): RequestResult<unknown, RetrieveAppTokenErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    RetrieveAppTokenErrors,
    ThrowOnError
  >({
    url: '/api/auth/app/retrieve_token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>
): RequestResult<unknown, unknown, ThrowOnError> =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: '/api/auth/test_token',
    ...options
  });

export const refreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshTokenData, ThrowOnError>
): RequestResult<unknown, RefreshTokenErrors, ThrowOnError> =>
  (options?.client ?? client).get<unknown, RefreshTokenErrors, ThrowOnError>({
    url: '/api/auth/refresh_token',
    ...options
  });

export const resetUserAvatar = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserAvatarData, ThrowOnError>
): RequestResult<
  ResetUserAvatarResponses,
  ResetUserAvatarErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    ResetUserAvatarResponses,
    ResetUserAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/management/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({ url: '/api/user/management', ...options });

export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editUser = <ThrowOnError extends boolean = false>(
  options: Options<EditUserData, ThrowOnError>
): RequestResult<EditUserResponses, EditUserErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const userInfo = <ThrowOnError extends boolean = false>(
  options: Options<UserInfoData, ThrowOnError>
): RequestResult<UserInfoResponses, UserInfoErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UserInfoResponses,
    UserInfoErrors,
    ThrowOnError
  >({ url: '/api/user/management/{uuid}', ...options });

export const mailActive = <ThrowOnError extends boolean = false>(
  options?: Options<MailActiveData, ThrowOnError>
): RequestResult<MailActiveResponses, MailActiveErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    MailActiveResponses,
    MailActiveErrors,
    ThrowOnError
  >({ url: '/api/user/management/mail', ...options });

export const listGroupsSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsSimpleData, ThrowOnError>
): RequestResult<
  ListGroupsSimpleResponses,
  ListGroupsSimpleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGroupsSimpleResponses,
    ListGroupsSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/groups', ...options });

export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>
): RequestResult<
  ResetUserPasswordResponses,
  ResetUserPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/management/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const changeUserEmail = <ThrowOnError extends boolean = false>(
  options: Options<ChangeUserEmailData, ThrowOnError>
): RequestResult<
  ChangeUserEmailResponses,
  ChangeUserEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ChangeUserEmailResponses,
    ChangeUserEmailErrors,
    ThrowOnError
  >({
    url: '/api/user/management/email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const convertOidcUser = <ThrowOnError extends boolean = false>(
  options: Options<ConvertOidcUserData, ThrowOnError>
): RequestResult<
  ConvertOidcUserResponses,
  ConvertOidcUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ConvertOidcUserResponses,
    ConvertOidcUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management/convert-oidc',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updatePassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordData, ThrowOnError>
): RequestResult<UpdatePasswordResponses, UpdatePasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdatePasswordResponses,
    UpdatePasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/account/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const startEmailChange = <ThrowOnError extends boolean = false>(
  options: Options<StartEmailChangeData, ThrowOnError>
): RequestResult<
  StartEmailChangeResponses,
  StartEmailChangeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    StartEmailChangeResponses,
    StartEmailChangeErrors,
    ThrowOnError
  >({
    url: '/api/user/account/email_change_start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>
): RequestResult<UpdateAccountResponses, UpdateAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdateAccountResponses,
    UpdateAccountErrors,
    ThrowOnError
  >({
    url: '/api/user/account/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const confirmEmailChange = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmEmailChangeData, ThrowOnError>
): RequestResult<
  ConfirmEmailChangeResponses,
  ConfirmEmailChangeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ConfirmEmailChangeResponses,
    ConfirmEmailChangeErrors,
    ThrowOnError
  >({
    url: '/api/user/account/email_change_confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAvatarData, ThrowOnError>
): RequestResult<UpdateAvatarResponses, UpdateAvatarErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdateAvatarResponses,
    UpdateAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/account/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const info = <ThrowOnError extends boolean = false>(
  options?: Options<InfoData, ThrowOnError>
): RequestResult<InfoResponses, InfoErrors, ThrowOnError> =>
  (options?.client ?? client).get<InfoResponses, InfoErrors, ThrowOnError>({
    url: '/api/user/info',
    ...options
  });

export const avatarById = <ThrowOnError extends boolean = false>(
  options: Options<AvatarByIdData, ThrowOnError>
): RequestResult<AvatarByIdResponses, AvatarByIdErrors, ThrowOnError> =>
  (options.client ?? client).get<
    AvatarByIdResponses,
    AvatarByIdErrors,
    ThrowOnError
  >({ url: '/api/user/info/avatar/{uuid}', ...options });

export const getMailSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetMailSettingsData, ThrowOnError>
): RequestResult<
  GetMailSettingsResponses,
  GetMailSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetMailSettingsResponses,
    GetMailSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/mail', ...options });

export const saveMailSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveMailSettingsData, ThrowOnError>
): RequestResult<
  SaveMailSettingsResponses,
  SaveMailSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SaveMailSettingsResponses,
    SaveMailSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/mail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const accountSettings = <ThrowOnError extends boolean = false>(
  options?: Options<AccountSettingsData, ThrowOnError>
): RequestResult<
  AccountSettingsResponses,
  AccountSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AccountSettingsResponses,
    AccountSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/account', ...options });

export const saveAccountSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveAccountSettingsData, ThrowOnError>
): RequestResult<
  SaveAccountSettingsResponses,
  SaveAccountSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SaveAccountSettingsResponses,
    SaveAccountSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/account',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const sendResetLink = <ThrowOnError extends boolean = false>(
  options: Options<SendResetLinkData, ThrowOnError>
): RequestResult<SendResetLinkResponses, SendResetLinkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SendResetLinkResponses,
    SendResetLinkErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
): RequestResult<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ResetPasswordResponses,
    ResetPasswordErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testMail = <ThrowOnError extends boolean = false>(
  options?: Options<TestMailData, ThrowOnError>
): RequestResult<TestMailResponses, TestMailErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TestMailResponses,
    TestMailErrors,
    ThrowOnError
  >({ url: '/api/mail/test', ...options });

export const deleteGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupData, ThrowOnError>
): RequestResult<DeleteGroupResponses, DeleteGroupErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteGroupResponses,
    DeleteGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listGroups = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsData, ThrowOnError>
): RequestResult<ListGroupsResponses, ListGroupsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListGroupsResponses,
    ListGroupsErrors,
    ThrowOnError
  >({ url: '/api/group', ...options });

export const createGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateGroupData, ThrowOnError>
): RequestResult<CreateGroupResponses, CreateGroupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateGroupResponses,
    CreateGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editGroup = <ThrowOnError extends boolean = false>(
  options: Options<EditGroupData, ThrowOnError>
): RequestResult<EditGroupResponses, EditGroupErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditGroupResponses,
    EditGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const groupInfo = <ThrowOnError extends boolean = false>(
  options: Options<GroupInfoData, ThrowOnError>
): RequestResult<GroupInfoResponses, GroupInfoErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GroupInfoResponses,
    GroupInfoErrors,
    ThrowOnError
  >({ url: '/api/group/{uuid}', ...options });

export const listUsersSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersSimpleData, ThrowOnError>
): RequestResult<
  ListUsersSimpleResponses,
  ListUsersSimpleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListUsersSimpleResponses,
    ListUsersSimpleErrors,
    ThrowOnError
  >({ url: '/api/group/users', ...options });

export const listApod = <ThrowOnError extends boolean = false>(
  options?: Options<ListApodData, ThrowOnError>
): RequestResult<ListApodResponses, ListApodErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListApodResponses,
    ListApodErrors,
    ThrowOnError
  >({ url: '/api/services/apod', ...options });

export const setGoodApod = <ThrowOnError extends boolean = false>(
  options: Options<SetGoodApodData, ThrowOnError>
): RequestResult<SetGoodApodResponses, SetGoodApodErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SetGoodApodResponses,
    SetGoodApodErrors,
    ThrowOnError
  >({
    url: '/api/services/apod',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getApodImageInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetApodImageInfoData, ThrowOnError>
): RequestResult<
  GetApodImageInfoResponses,
  GetApodImageInfoErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    GetApodImageInfoResponses,
    GetApodImageInfoErrors,
    ThrowOnError
  >({
    url: '/api/services/apod/get_image_info',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getApodImage = <ThrowOnError extends boolean = false>(
  options: Options<GetApodImageData, ThrowOnError>
): RequestResult<unknown, GetApodImageErrors, ThrowOnError> =>
  (options.client ?? client).get<unknown, GetApodImageErrors, ThrowOnError>({
    url: '/api/services/apod/get_image',
    ...options
  });

export const authorizeConfirm = <ThrowOnError extends boolean = false>(
  options: Options<AuthorizeConfirmData, ThrowOnError>
): RequestResult<
  AuthorizeConfirmResponses,
  AuthorizeConfirmErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthorizeConfirmResponses,
    AuthorizeConfirmErrors,
    ThrowOnError
  >({ url: '/api/oauth/authorize_confirm', ...options });

export const deleteOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOauthClientData, ThrowOnError>
): RequestResult<
  DeleteOauthClientResponses,
  DeleteOauthClientErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOauthClientResponses,
    DeleteOauthClientErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/client',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listOauthClients = <ThrowOnError extends boolean = false>(
  options?: Options<ListOauthClientsData, ThrowOnError>
): RequestResult<
  ListOauthClientsResponses,
  ListOauthClientsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListOauthClientsResponses,
    ListOauthClientsErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client', ...options });

export const createOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<CreateOauthClientData, ThrowOnError>
): RequestResult<
  CreateOauthClientResponses,
  CreateOauthClientErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOauthClientResponses,
    CreateOauthClientErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/client',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<EditOauthClientData, ThrowOnError>
): RequestResult<
  EditOauthClientResponses,
  EditOauthClientErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    EditOauthClientResponses,
    EditOauthClientErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/client',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const infoOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<InfoOauthClientData, ThrowOnError>
): RequestResult<
  InfoOauthClientResponses,
  InfoOauthClientErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    InfoOauthClientResponses,
    InfoOauthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/{uuid}', ...options });

export const regenerateSecretOauthClient = <
  ThrowOnError extends boolean = false
>(
  options: Options<RegenerateSecretOauthClientData, ThrowOnError>
): RequestResult<
  RegenerateSecretOauthClientResponses,
  RegenerateSecretOauthClientErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegenerateSecretOauthClientResponses,
    RegenerateSecretOauthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/{uuid}', ...options });

export const siteUrl = <ThrowOnError extends boolean = false>(
  options?: Options<SiteUrlData, ThrowOnError>
): RequestResult<SiteUrlResponses, SiteUrlErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    SiteUrlResponses,
    SiteUrlErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/site_url', ...options });

export const listGroupsOAuthClient = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsOAuthClientData, ThrowOnError>
): RequestResult<
  ListGroupsOAuthClientResponses,
  ListGroupsOAuthClientErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGroupsOAuthClientResponses,
    ListGroupsOAuthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/groups', ...options });

export const listUsersOAuthClient = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersOAuthClientData, ThrowOnError>
): RequestResult<
  ListUsersOAuthClientResponses,
  ListUsersOAuthClientErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListUsersOAuthClientResponses,
    ListUsersOAuthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/users', ...options });

export const listScopesOAuthClient = <ThrowOnError extends boolean = false>(
  options?: Options<ListScopesOAuthClientData, ThrowOnError>
): RequestResult<
  ListScopesOAuthClientResponses,
  ListScopesOAuthClientErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListScopesOAuthClientResponses,
    ListScopesOAuthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/scopes', ...options });

export const deleteOAuthScope = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOAuthScopeData, ThrowOnError>
): RequestResult<
  DeleteOAuthScopeResponses,
  DeleteOAuthScopeErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOAuthScopeResponses,
    DeleteOAuthScopeErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/scope',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listOAuthScopes = <ThrowOnError extends boolean = false>(
  options?: Options<ListOAuthScopesData, ThrowOnError>
): RequestResult<
  ListOAuthScopesResponses,
  ListOAuthScopesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListOAuthScopesResponses,
    ListOAuthScopesErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/scope', ...options });

export const createOAuthScope = <ThrowOnError extends boolean = false>(
  options: Options<CreateOAuthScopeData, ThrowOnError>
): RequestResult<
  CreateOAuthScopeResponses,
  CreateOAuthScopeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOAuthScopeResponses,
    CreateOAuthScopeErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/scope',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editOAuthScope = <ThrowOnError extends boolean = false>(
  options: Options<EditOAuthScopeData, ThrowOnError>
): RequestResult<EditOAuthScopeResponses, EditOAuthScopeErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditOAuthScopeResponses,
    EditOAuthScopeErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/scope',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const infoOAuthScope = <ThrowOnError extends boolean = false>(
  options: Options<InfoOAuthScopeData, ThrowOnError>
): RequestResult<InfoOAuthScopeResponses, InfoOAuthScopeErrors, ThrowOnError> =>
  (options.client ?? client).get<
    InfoOAuthScopeResponses,
    InfoOAuthScopeErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/scope/{uuid}', ...options });

export const listPoliciesOAuthScope = <ThrowOnError extends boolean = false>(
  options?: Options<ListPoliciesOAuthScopeData, ThrowOnError>
): RequestResult<
  ListPoliciesOAuthScopeResponses,
  ListPoliciesOAuthScopeErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListPoliciesOAuthScopeResponses,
    ListPoliciesOAuthScopeErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/scope/policies', ...options });

export const deleteOAuthPolicy = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOAuthPolicyData, ThrowOnError>
): RequestResult<
  DeleteOAuthPolicyResponses,
  DeleteOAuthPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOAuthPolicyResponses,
    DeleteOAuthPolicyErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/policy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listOAuthPolicies = <ThrowOnError extends boolean = false>(
  options?: Options<ListOAuthPoliciesData, ThrowOnError>
): RequestResult<
  ListOAuthPoliciesResponses,
  ListOAuthPoliciesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListOAuthPoliciesResponses,
    ListOAuthPoliciesErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/policy', ...options });

export const createOAuthPolicy = <ThrowOnError extends boolean = false>(
  options: Options<CreateOAuthPolicyData, ThrowOnError>
): RequestResult<
  CreateOAuthPolicyResponses,
  CreateOAuthPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOAuthPolicyResponses,
    CreateOAuthPolicyErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/policy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editOAuthPolicy = <ThrowOnError extends boolean = false>(
  options: Options<EditOAuthPolicyData, ThrowOnError>
): RequestResult<
  EditOAuthPolicyResponses,
  EditOAuthPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    EditOAuthPolicyResponses,
    EditOAuthPolicyErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/policy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const infoOAuthPolicy = <ThrowOnError extends boolean = false>(
  options: Options<InfoOAuthPolicyData, ThrowOnError>
): RequestResult<
  InfoOAuthPolicyResponses,
  InfoOAuthPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    InfoOAuthPolicyResponses,
    InfoOAuthPolicyErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/policy/{uuid}', ...options });

export const listGroupsOAuthPolicy = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsOAuthPolicyData, ThrowOnError>
): RequestResult<
  ListGroupsOAuthPolicyResponses,
  ListGroupsOAuthPolicyErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGroupsOAuthPolicyResponses,
    ListGroupsOAuthPolicyErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/policy/groups', ...options });

export const deleteNote = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNoteData, ThrowOnError>
): RequestResult<DeleteNoteResponses, DeleteNoteErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteNoteResponses,
    DeleteNoteErrors,
    ThrowOnError
  >({
    url: '/api/notes/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listNotes = <ThrowOnError extends boolean = false>(
  options?: Options<ListNotesData, ThrowOnError>
): RequestResult<ListNotesResponses, ListNotesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListNotesResponses,
    ListNotesErrors,
    ThrowOnError
  >({ url: '/api/notes/management', ...options });

export const createNote = <ThrowOnError extends boolean = false>(
  options: Options<CreateNoteData, ThrowOnError>
): RequestResult<CreateNoteResponses, CreateNoteErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateNoteResponses,
    CreateNoteErrors,
    ThrowOnError
  >({
    url: '/api/notes/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editNote = <ThrowOnError extends boolean = false>(
  options: Options<EditNoteData, ThrowOnError>
): RequestResult<EditNoteResponses, EditNoteErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditNoteResponses,
    EditNoteErrors,
    ThrowOnError
  >({
    url: '/api/notes/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const infoNote = <ThrowOnError extends boolean = false>(
  options: Options<InfoNoteData, ThrowOnError>
): RequestResult<InfoNoteResponses, InfoNoteErrors, ThrowOnError> =>
  (options.client ?? client).get<
    InfoNoteResponses,
    InfoNoteErrors,
    ThrowOnError
  >({ url: '/api/notes/management/{uuid}', ...options });

export const listUsersNote = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersNoteData, ThrowOnError>
): RequestResult<ListUsersNoteResponses, ListUsersNoteErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListUsersNoteResponses,
    ListUsersNoteErrors,
    ThrowOnError
  >({ url: '/api/notes/management/users', ...options });

export const shareNote = <ThrowOnError extends boolean = false>(
  options: Options<ShareNoteData, ThrowOnError>
): RequestResult<ShareNoteResponses, ShareNoteErrors, ThrowOnError> =>
  (options.client ?? client).put<
    ShareNoteResponses,
    ShareNoteErrors,
    ThrowOnError
  >({
    url: '/api/notes/management/share',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });
