// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AccountSettingsData,
  AccountSettingsErrors,
  AccountSettingsResponses,
  AuthConfigData,
  AuthConfigErrors,
  AuthConfigResponses,
  AvatarByIdData,
  AvatarByIdErrors,
  AvatarByIdResponses,
  ChangePasswordData,
  ChangePasswordErrors,
  ChangeUserEmailData,
  ChangeUserEmailErrors,
  ChangeUserEmailResponses,
  CompleteSetupData,
  CompleteSetupErrors,
  ConfirmEmailChangeData,
  ConfirmEmailChangeErrors,
  ConfirmEmailChangeResponses,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupResponses,
  CreateOauthClientData,
  CreateOauthClientErrors,
  CreateOauthClientResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupResponses,
  DeleteOauthClientData,
  DeleteOauthClientErrors,
  DeleteOauthClientResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  EditGroupData,
  EditGroupErrors,
  EditGroupResponses,
  EditOauthClientData,
  EditOauthClientErrors,
  EditOauthClientResponses,
  EditPasskeyNameData,
  EditPasskeyNameErrors,
  EditPasskeyNameResponses,
  EditUserData,
  EditUserErrors,
  EditUserResponses,
  FinishAuthenticationData,
  FinishAuthenticationErrors,
  FinishRegistrationData,
  FinishRegistrationErrors,
  FinishSpecialAccessData,
  FinishSpecialAccessErrors,
  GetApodImageData,
  GetApodImageErrors,
  GetApodImageInfoData,
  GetApodImageInfoErrors,
  GetApodImageInfoResponses,
  GetApodImageResponses,
  GetMailSettingsData,
  GetMailSettingsErrors,
  GetMailSettingsResponses,
  GroupInfoData,
  GroupInfoErrors,
  GroupInfoResponses,
  InfoData,
  InfoErrors,
  InfoOauthClientData,
  InfoOauthClientErrors,
  InfoOauthClientResponses,
  InfoResponses,
  IsSetupData,
  IsSetupErrors,
  IsSetupResponses,
  KeyData,
  KeyResponses,
  ListApodData,
  ListApodErrors,
  ListApodResponses,
  ListGroupsData,
  ListGroupsErrors,
  ListGroupsOAuthClientData,
  ListGroupsOAuthClientErrors,
  ListGroupsOAuthClientResponses,
  ListGroupsResponses,
  ListGroupsSimpleData,
  ListGroupsSimpleErrors,
  ListGroupsSimpleResponses,
  ListOauthClientsData,
  ListOauthClientsErrors,
  ListOauthClientsResponses,
  ListPasskeysData,
  ListPasskeysErrors,
  ListPasskeysResponses,
  ListScopesOAuthClientData,
  ListScopesOAuthClientErrors,
  ListScopesOAuthClientResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersOAuthClientData,
  ListUsersOAuthClientErrors,
  ListUsersOAuthClientResponses,
  ListUsersResponses,
  ListUsersSimpleData,
  ListUsersSimpleErrors,
  ListUsersSimpleResponses,
  LogoutData,
  LogoutErrors,
  MailActiveData,
  MailActiveErrors,
  MailActiveResponses,
  PasswordAuthenticateData,
  PasswordAuthenticateErrors,
  PasswordSpecialAccessData,
  PasswordSpecialAccessErrors,
  RemovePasskeyData,
  RemovePasskeyErrors,
  RemovePasskeyResponses,
  ResetPasswordData,
  ResetPasswordErrors,
  ResetPasswordResponses,
  ResetUserAvatarData,
  ResetUserAvatarErrors,
  ResetUserAvatarResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  SaveAccountSettingsData,
  SaveAccountSettingsErrors,
  SaveAccountSettingsResponses,
  SaveMailSettingsData,
  SaveMailSettingsErrors,
  SaveMailSettingsResponses,
  SendResetLinkData,
  SendResetLinkErrors,
  SendResetLinkResponses,
  SetGoodApodData,
  SetGoodApodErrors,
  SetGoodApodResponses,
  StartAuthenticationData,
  StartAuthenticationErrors,
  StartAuthenticationResponses,
  StartEmailChangeData,
  StartEmailChangeErrors,
  StartEmailChangeResponses,
  StartRegistrationData,
  StartRegistrationErrors,
  StartRegistrationResponses,
  StartSpecialAccessData,
  StartSpecialAccessErrors,
  StartSpecialAccessResponses,
  TestMailData,
  TestMailErrors,
  TestMailResponses,
  TestTokenData,
  TotpConfirmData,
  TotpConfirmErrors,
  TotpFinishSetupData,
  TotpFinishSetupErrors,
  TotpRemoveData,
  TotpRemoveErrors,
  TotpStartSetupData,
  TotpStartSetupErrors,
  TotpStartSetupResponses,
  UpdateAccountData,
  UpdateAccountErrors,
  UpdateAccountResponses,
  UpdateAvatarData,
  UpdateAvatarErrors,
  UpdateAvatarResponses,
  UpdatePasswordData,
  UpdatePasswordErrors,
  UpdatePasswordResponses,
  UserInfoData,
  UserInfoErrors,
  UserInfoResponses
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const isSetup = <ThrowOnError extends boolean = false>(
  options?: Options<IsSetupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    IsSetupResponses,
    IsSetupErrors,
    ThrowOnError
  >({ url: '/api/setup', ...options });

export const completeSetup = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSetupData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, CompleteSetupErrors, ThrowOnError>({
    url: '/api/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<unknown, LogoutErrors, ThrowOnError>({
    url: '/api/auth/logout',
    ...options
  });

export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>
) =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: '/api/auth/test_token',
    ...options
  });

export const finishRegistration = <ThrowOnError extends boolean = false>(
  options: Options<FinishRegistrationData, ThrowOnError>
) =>
  (options.client ?? client).post<
    unknown,
    FinishRegistrationErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/finish_registration',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const finishAuthentication = <ThrowOnError extends boolean = false>(
  options: Options<FinishAuthenticationData, ThrowOnError>
) =>
  (options.client ?? client).post<
    unknown,
    FinishAuthenticationErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/finish_authentication/{auth_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const finishSpecialAccess = <ThrowOnError extends boolean = false>(
  options: Options<FinishSpecialAccessData, ThrowOnError>
) =>
  (options.client ?? client).post<
    unknown,
    FinishSpecialAccessErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/finish_special_access',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const startRegistration = <ThrowOnError extends boolean = false>(
  options?: Options<StartRegistrationData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    StartRegistrationResponses,
    StartRegistrationErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/start_registration', ...options });

export const startAuthentication = <ThrowOnError extends boolean = false>(
  options?: Options<StartAuthenticationData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    StartAuthenticationResponses,
    StartAuthenticationErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/start_authentication', ...options });

export const startSpecialAccess = <ThrowOnError extends boolean = false>(
  options?: Options<StartSpecialAccessData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    StartSpecialAccessResponses,
    StartSpecialAccessErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/start_special_access', ...options });

export const listPasskeys = <ThrowOnError extends boolean = false>(
  options?: Options<ListPasskeysData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPasskeysResponses,
    ListPasskeysErrors,
    ThrowOnError
  >({ url: '/api/auth/passkey/list', ...options });

export const removePasskey = <ThrowOnError extends boolean = false>(
  options: Options<RemovePasskeyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RemovePasskeyResponses,
    RemovePasskeyErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editPasskeyName = <ThrowOnError extends boolean = false>(
  options: Options<EditPasskeyNameData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EditPasskeyNameResponses,
    EditPasskeyNameErrors,
    ThrowOnError
  >({
    url: '/api/auth/passkey/edit_name',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const passwordAuthenticate = <ThrowOnError extends boolean = false>(
  options: Options<PasswordAuthenticateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    unknown,
    PasswordAuthenticateErrors,
    ThrowOnError
  >({
    url: '/api/auth/password/authenticate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const passwordSpecialAccess = <ThrowOnError extends boolean = false>(
  options: Options<PasswordSpecialAccessData, ThrowOnError>
) =>
  (options.client ?? client).post<
    unknown,
    PasswordSpecialAccessErrors,
    ThrowOnError
  >({
    url: '/api/auth/password/special_access',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const key = <ThrowOnError extends boolean = false>(
  options?: Options<KeyData, ThrowOnError>
) =>
  (options?.client ?? client).get<KeyResponses, unknown, ThrowOnError>({
    url: '/api/auth/password/key',
    ...options
  });

export const changePassword = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, ChangePasswordErrors, ThrowOnError>({
    url: '/api/auth/password/change',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const totpConfirm = <ThrowOnError extends boolean = false>(
  options: Options<TotpConfirmData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, TotpConfirmErrors, ThrowOnError>({
    url: '/api/auth/totp/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const totpStartSetup = <ThrowOnError extends boolean = false>(
  options?: Options<TotpStartSetupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    TotpStartSetupResponses,
    TotpStartSetupErrors,
    ThrowOnError
  >({ url: '/api/auth/totp/start_setup', ...options });

export const totpFinishSetup = <ThrowOnError extends boolean = false>(
  options: Options<TotpFinishSetupData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, TotpFinishSetupErrors, ThrowOnError>(
    {
      url: '/api/auth/totp/finish_setup',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers
      }
    }
  );

export const totpRemove = <ThrowOnError extends boolean = false>(
  options?: Options<TotpRemoveData, ThrowOnError>
) =>
  (options?.client ?? client).post<unknown, TotpRemoveErrors, ThrowOnError>({
    url: '/api/auth/totp/remove',
    ...options
  });

export const authConfig = <ThrowOnError extends boolean = false>(
  options?: Options<AuthConfigData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthConfigResponses,
    AuthConfigErrors,
    ThrowOnError
  >({ url: '/api/auth/config', ...options });

export const resetUserAvatar = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserAvatarData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ResetUserAvatarResponses,
    ResetUserAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/management/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({ url: '/api/user/management', ...options });

export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editUser = <ThrowOnError extends boolean = false>(
  options: Options<EditUserData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const userInfo = <ThrowOnError extends boolean = false>(
  options: Options<UserInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserInfoResponses,
    UserInfoErrors,
    ThrowOnError
  >({ url: '/api/user/management/{uuid}', ...options });

export const mailActive = <ThrowOnError extends boolean = false>(
  options?: Options<MailActiveData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    MailActiveResponses,
    MailActiveErrors,
    ThrowOnError
  >({ url: '/api/user/management/mail', ...options });

export const listGroupsSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsSimpleResponses,
    ListGroupsSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/groups', ...options });

export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/management/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const changeUserEmail = <ThrowOnError extends boolean = false>(
  options: Options<ChangeUserEmailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ChangeUserEmailResponses,
    ChangeUserEmailErrors,
    ThrowOnError
  >({
    url: '/api/user/management/email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAvatarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateAvatarResponses,
    UpdateAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/account/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updatePassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdatePasswordResponses,
    UpdatePasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/account/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const startEmailChange = <ThrowOnError extends boolean = false>(
  options: Options<StartEmailChangeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    StartEmailChangeResponses,
    StartEmailChangeErrors,
    ThrowOnError
  >({
    url: '/api/user/account/email_change_start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateAccountResponses,
    UpdateAccountErrors,
    ThrowOnError
  >({
    url: '/api/user/account/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const confirmEmailChange = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmEmailChangeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ConfirmEmailChangeResponses,
    ConfirmEmailChangeErrors,
    ThrowOnError
  >({
    url: '/api/user/account/email_change_confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const info = <ThrowOnError extends boolean = false>(
  options?: Options<InfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<InfoResponses, InfoErrors, ThrowOnError>({
    url: '/api/user/info',
    ...options
  });

export const avatarById = <ThrowOnError extends boolean = false>(
  options: Options<AvatarByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AvatarByIdResponses,
    AvatarByIdErrors,
    ThrowOnError
  >({ url: '/api/user/info/avatar/{uuid}', ...options });

export const getMailSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetMailSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetMailSettingsResponses,
    GetMailSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/mail', ...options });

export const saveMailSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveMailSettingsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveMailSettingsResponses,
    SaveMailSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/mail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const accountSettings = <ThrowOnError extends boolean = false>(
  options?: Options<AccountSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AccountSettingsResponses,
    AccountSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/account', ...options });

export const saveAccountSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveAccountSettingsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveAccountSettingsResponses,
    SaveAccountSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/account',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const sendResetLink = <ThrowOnError extends boolean = false>(
  options: Options<SendResetLinkData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SendResetLinkResponses,
    SendResetLinkErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ResetPasswordResponses,
    ResetPasswordErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testMail = <ThrowOnError extends boolean = false>(
  options?: Options<TestMailData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    TestMailResponses,
    TestMailErrors,
    ThrowOnError
  >({ url: '/api/mail/test', ...options });

export const deleteGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteGroupResponses,
    DeleteGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listGroups = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsResponses,
    ListGroupsErrors,
    ThrowOnError
  >({ url: '/api/group', ...options });

export const createGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateGroupData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateGroupResponses,
    CreateGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editGroup = <ThrowOnError extends boolean = false>(
  options: Options<EditGroupData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditGroupResponses,
    EditGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const groupInfo = <ThrowOnError extends boolean = false>(
  options: Options<GroupInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GroupInfoResponses,
    GroupInfoErrors,
    ThrowOnError
  >({ url: '/api/group/{uuid}', ...options });

export const listUsersSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersSimpleResponses,
    ListUsersSimpleErrors,
    ThrowOnError
  >({ url: '/api/group/users', ...options });

export const listApod = <ThrowOnError extends boolean = false>(
  options?: Options<ListApodData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListApodResponses,
    ListApodErrors,
    ThrowOnError
  >({ url: '/api/services/apod', ...options });

export const setGoodApod = <ThrowOnError extends boolean = false>(
  options: Options<SetGoodApodData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SetGoodApodResponses,
    SetGoodApodErrors,
    ThrowOnError
  >({
    url: '/api/services/apod',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getApodImageInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetApodImageInfoData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GetApodImageInfoResponses,
    GetApodImageInfoErrors,
    ThrowOnError
  >({
    url: '/api/services/apod/get_image_info',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getApodImage = <ThrowOnError extends boolean = false>(
  options: Options<GetApodImageData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GetApodImageResponses,
    GetApodImageErrors,
    ThrowOnError
  >({
    url: '/api/services/apod/get_image',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const deleteOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOauthClientData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteOauthClientResponses,
    DeleteOauthClientErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/client',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listOauthClients = <ThrowOnError extends boolean = false>(
  options?: Options<ListOauthClientsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListOauthClientsResponses,
    ListOauthClientsErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client', ...options });

export const createOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<CreateOauthClientData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateOauthClientResponses,
    CreateOauthClientErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/client',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<EditOauthClientData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditOauthClientResponses,
    EditOauthClientErrors,
    ThrowOnError
  >({
    url: '/api/oauth_management/client',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listGroupsOAuthClient = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsOAuthClientData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsOAuthClientResponses,
    ListGroupsOAuthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/groups', ...options });

export const listUsersOAuthClient = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersOAuthClientData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersOAuthClientResponses,
    ListUsersOAuthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/users', ...options });

export const listScopesOAuthClient = <ThrowOnError extends boolean = false>(
  options?: Options<ListScopesOAuthClientData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListScopesOAuthClientResponses,
    ListScopesOAuthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/scopes', ...options });

export const infoOauthClient = <ThrowOnError extends boolean = false>(
  options: Options<InfoOauthClientData, ThrowOnError>
) =>
  (options.client ?? client).get<
    InfoOauthClientResponses,
    InfoOauthClientErrors,
    ThrowOnError
  >({ url: '/api/oauth_management/client/{uuid}', ...options });
