// This file is auto-generated by @hey-api/openapi-ts

import type { ListApodResponse, ListPasskeysResponse } from './types.gen';

const passkeyInfoSchemaResponseTransformer = (data: any) => {
  data.created = new Date(data.created);
  data.used = new Date(data.used);
  return data;
};

export const listPasskeysResponseTransformer = async (
  data: any
): Promise<ListPasskeysResponse> => {
  data = data.map((item: any) => passkeyInfoSchemaResponseTransformer(item));
  return data;
};

const apodInfoSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  return data;
};

export const listApodResponseTransformer = async (
  data: any
): Promise<ListApodResponse> => {
  data = data.map((item: any) => apodInfoSchemaResponseTransformer(item));
  return data;
};
