// This file is auto-generated by @hey-api/openapi-ts

import type {
  ListApodResponse,
  ListPasskeysResponse,
  ListSessionsResponse
} from './types.gen';

const passkeyInfoSchemaResponseTransformer = (data: any) => {
  data.created = new Date(data.created);
  data.used = new Date(data.used);
  return data;
};

export const listPasskeysResponseTransformer = async (
  data: any
): Promise<ListPasskeysResponse> => {
  data = data.map((item: any) => passkeyInfoSchemaResponseTransformer(item));
  return data;
};

const sessionInfoSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.expires_at = new Date(data.expires_at);
  data.last_used_at = new Date(data.last_used_at);
  if (data.refreshed_at) {
    data.refreshed_at = new Date(data.refreshed_at);
  }
  return data;
};

export const listSessionsResponseTransformer = async (
  data: any
): Promise<ListSessionsResponse> => {
  data = data.map((item: any) => sessionInfoSchemaResponseTransformer(item));
  return data;
};

const apodInfoSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  return data;
};

export const listApodResponseTransformer = async (
  data: any
): Promise<ListApodResponse> => {
  data = data.map((item: any) => apodInfoSchemaResponseTransformer(item));
  return data;
};
