// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5175' | (string & {});
};

export type AccountUpdate = {
  username: string;
};

export type ApodInfo = {
  date: Date;
  title: string;
  user: SimpleUserInfo;
};

export type ApproveCodeReq = {
  code: string;
};

export type AuthConfig = {
  mail_enabled: boolean;
};

export type AuthConfirmQuery = {
  allow?: boolean | null;
  code: string;
};

export type AuthReq = {
  application: string;
  name: string;
  operating_system: string;
};

export type AuthRes = {
  location: string;
};

export type AuthStartRes = {
  id: string;
};

export type AvatarPath = {
  uuid: string;
};

export type AvatarUpdate = {
  avatar: string;
};

export type ChangeUserEmail = {
  new_email: string;
  uuid: string;
};

export type ClientCreate = {
  confidential: boolean;
  name: string;
  redirect_uri: string;
  require_pkce: boolean;
  scope: Array<string>;
};

export type ClientCreateRes = {
  client_id: string;
  client_secret: string;
};

export type CodeReq = {
  challenge: string;
};

export type CodeRes = {
  code: string;
};

export type CreateGroupRequest = {
  name: string;
};

export type CreateReq = {
  name: string;
  policies: Array<string>;
  scope: string;
};

export type CreateReq2 = {
  claim: string;
  default: string;
  name: string;
};

export type CreateRes = {
  uuid: string;
};

export type CreateRes2 = {
  uuid: string;
};

export type CreateUser = {
  email: string;
  name: string;
  password?: string | null;
};

export type CreateUserResponse = {
  uuid: string;
};

export type DeleteClientRequest = {
  client_id: string;
};

export type DeleteGroupRequest = {
  uuid: string;
};

export type DeleteReq = {
  uuid: string;
};

export type DeleteReq2 = {
  uuid: string;
};

export type DeleteUserRequest = {
  uuid: string;
};

export type DetailUserInfo = {
  email: string;
  groups: Array<SimpleGroupInfo>;
  name: string;
  oidc_user: boolean;
  permissions: Array<string>;
  uuid: string;
};

export type EditGroupRequest = {
  name: string;
  permissions: Array<string>;
  users: Array<string>;
  uuid: string;
};

export type EmailChange = {
  new_email: string;
};

export type EmailChangeConfirm = {
  new_code: string;
  old_code: string;
};

export type ExchangeCodeReq = {
  application: string;
  code: string;
  name: string;
  operating_system: string;
  verifier: string;
};

export type FinishAuthPath = {
  auth_id: string;
};

export type GetImageReq = {
  date: Date;
  preview?: boolean | null;
};

export type GetInfoReq = {
  date: Date;
};

export type GetInfoRes = {
  title: string;
  user?: SimpleUserInfo | null;
};

export type GroupCreateResponse = {
  uuid: string;
};

export type GroupDetails = {
  id: string;
  name: string;
  permissions: Array<string>;
  users: Array<SimpleUserInfo>;
};

export type GroupDetailsResponse = {
  admin_group: string;
  group: GroupDetails;
};

export type GroupInfo = {
  id: string;
  name: string;
  permissions: Array<string>;
  users: Array<SimpleUserInfo>;
};

export type GroupViewPath = {
  uuid: string;
};

export type IsSetupResponse = {
  db_backend: string;
  is_setup: boolean;
  storage_backend: string;
};

export type KeyRes = {
  key: string;
};

export type ListGroupResponse = {
  admin_group?: string | null;
  groups: Array<GroupInfo>;
};

export type LoginReq = {
  application: string;
  email: string;
  name: string;
  operating_system: string;
  password: string;
};

export type MailActiveResponse = {
  active: boolean;
};

export type MailSettings = {
  smtp_enabled?: boolean | null;
  smtp_from_address?: string | null;
  smtp_from_name?: string | null;
  smtp_password?: string | null;
  smtp_port?: number | null;
  smtp_server?: string | null;
  smtp_use_tls?: boolean | null;
  smtp_username?: string | null;
};

export type MailSettingsResponse = {
  from_env: Array<string>;
  settings: MailSettings;
};

export type NoteCreateReq = {
  title: string;
};

export type NoteCreateRes = {
  id: string;
};

export type NoteDeleteReq = {
  note_id: string;
};

export type NoteEditReq = {
  note_id: string;
  title: string;
};

export type NoteInfo = {
  can_edit: boolean;
  id: string;
  is_owner: boolean;
  owner: SimpleUserInfo;
  preview: string;
  public_access?: NoteShareAccess | null;
  shared_with: Array<SharedUserInfo>;
  title: string;
};

export type NoteInfoPublic = {
  can_edit: boolean;
  id: string;
  owner: SimpleUserInfo;
  title: string;
};

export type NotePath = {
  uuid: string;
};

export type NotePath2 = {
  note_uuid: string;
};

export type NotePublicShareReq = {
  note_id: string;
  public_access?: NoteShareAccess | null;
};

export const NoteShareAccess = { VIEW: 'view', EDIT: 'edit' } as const;

export type NoteShareAccess =
  (typeof NoteShareAccess)[keyof typeof NoteShareAccess];

export type NoteShareEntry = {
  access: NoteShareAccess;
  user_id: string;
};

export type NoteShareReq = {
  note_id: string;
  shared_with: Array<NoteShareEntry>;
};

export type NoteSnapshotDetail = {
  created_at: string;
  note_id: string;
  title: string;
};

export type NoteSnapshotIdReq = {
  snapshot_id: string;
};

export type NoteSnapshotInfo = {
  created_at: string;
  id: string;
  note_id: string;
  preview: string;
};

export type NoteTransferReq = {
  new_owner_id: string;
  note_id: string;
};

export type NotesConfigRes = {
  max_per_user: number;
};

export type OAuthClientEditReq = {
  additional_redirect_uris: Array<string>;
  client_id: string;
  group_access: Array<string>;
  name: string;
  redirect_uri: string;
  require_pkce: boolean;
  scope: Array<string>;
  user_access: Array<string>;
};

export type OAuthClientInfo = {
  additional_redirect_uris: Array<string>;
  client_id: string;
  confidential: boolean;
  default_scope: Array<SimpleOAuthScopeInfo>;
  group_access: Array<SimpleGroupInfo>;
  name: string;
  redirect_uri: string;
  require_pkce: boolean;
  user_access: Array<SimpleUserInfo>;
};

export type OAuthClientPath = {
  uuid: string;
};

export type OAuthPolicyContent = {
  content: string;
  group_id: string;
  group_name: string;
  index: number;
};

export type OAuthPolicyInfo = {
  claim: string;
  content: Array<OAuthPolicyContent>;
  default: string;
  name: string;
  uuid: string;
};

export type OAuthPolicyPath = {
  uuid: string;
};

export type OAuthRegenerateResponse = {
  secret: string;
};

export type OAuthScopeEditReq = {
  name: string;
  policies: Array<string>;
  scope: string;
  uuid: string;
};

export type OAuthScopeInfo = {
  name: string;
  policies: Array<SimpleOAuthPolicyInfo>;
  scope: string;
  uuid: string;
};

export type OAuthScopePath = {
  uuid: string;
};

export type OidcSetupResponse = {
  from_env: Array<string>;
  settings: UserSettings;
  site_url: string;
};

export type PasskeyEdit = {
  name: string;
  old_name: string;
};

export type PasskeyInfo = {
  created: Date;
  name: string;
  used: Date;
};

export type PasskeyRemove = {
  name: string;
};

export type PasswordChange = {
  password: string;
  password_confirm: string;
};

export type PasswordUpdate = {
  new_password: string;
  old_password: string;
};

export type RegFinishReq = {
  name: string;
};

export type ResetPasswordPayload = {
  new_password: string;
  token: string;
};

export type ResetRequest = {
  email: string;
};

export type ResetUserPassword = {
  new_password: string;
  uuid: string;
};

export type RetrieveTokenReq = {
  application: string;
  auth_code: string;
  name: string;
  operating_system: string;
  verifier: string;
};

export type RevokeSessionReq = {
  id: string;
};

export type SessionInfo = {
  application: string;
  created_at: Date;
  current: boolean;
  expires_at: Date;
  id: string;
  is_app: boolean;
  last_used_at: Date;
  name: string;
  operating_system: string;
  refreshed_at?: Date | null;
};

export type SetGoodReq = {
  date: Date;
  good: boolean;
};

export type SettingsInfo = {
  o_auth_instant_confirm: boolean;
};

export type SetupPayload = {
  admin_email: string;
  admin_password: string;
  admin_username: string;
  application: string;
  name: string;
  operating_system: string;
};

export type SharedUserInfo = {
  access: NoteShareAccess;
  id: string;
  name: string;
};

export type SimpleGroupInfo = {
  name: string;
  uuid: string;
};

export type SimpleOAuthPolicyInfo = {
  name: string;
  uuid: string;
};

export type SimpleOAuthScopeInfo = {
  name: string;
  scope: string;
  uuid: string;
};

export type SimpleUserInfo = {
  id: string;
  name: string;
};

export type SiteUrlResponse = {
  url: string;
};

export type SnapshotPath = {
  snapshot_id: string;
};

export type SpecialAccess = {
  password: string;
};

export type TotpConfirmReq = {
  application: string;
  code: string;
  name: string;
  operating_system: string;
};

export type TotpReq = {
  code: string;
};

export type TotpSetupRes = {
  code: string;
  qr: string;
};

export type UserAvatarResetRequest = {
  uuid: string;
};

export type UserEditReq = {
  groups: Array<string>;
  name: string;
  uuid: string;
};

export type UserInfo = {
  email: string;
  name: string;
  permissions: Array<string>;
  totp_enabled: boolean;
  uuid: string;
};

export type UserListInfo = {
  email: string;
  groups: Array<SimpleGroupInfo>;
  name: string;
  uuid: string;
};

export type UserSettings = {
  oidc_client_id?: string | null;
  oidc_client_secret?: string | null;
  oidc_enabled?: boolean | null;
  oidc_group_claim?: string | null;
  oidc_group_sync?: boolean | null;
  oidc_image_sync?: boolean | null;
  oidc_issuer?: string | null;
  oidc_pkce?: boolean | null;
  oidc_scopes?: string | null;
  sso_create_user?: boolean | null;
  sso_instant_redirect?: boolean | null;
};

export type UserViewPath = {
  uuid: string;
};

export type IsSetupData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/setup';
};

export type IsSetupErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type IsSetupResponses = {
  200: IsSetupResponse;
};

export type IsSetupResponse2 = IsSetupResponses[keyof IsSetupResponses];

export type CompleteSetupData = {
  body: SetupPayload;
  path?: never;
  query?: never;
  url: '/api/setup';
};

export type CompleteSetupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CompleteSetupError = CompleteSetupErrors[keyof CompleteSetupErrors];

export type GetOidcSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/setup/oidc';
};

export type GetOidcSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetOidcSettingsResponses = {
  200: OidcSetupResponse;
};

export type GetOidcSettingsResponse =
  GetOidcSettingsResponses[keyof GetOidcSettingsResponses];

export type InitOidcData = {
  body: UserSettings;
  path?: never;
  query?: never;
  url: '/api/setup/oidc';
};

export type InitOidcErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InitOidcError = InitOidcErrors[keyof InitOidcErrors];

export type InitOidcResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishRegistrationData = {
  body: RegFinishReq;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/finish_registration';
};

export type FinishRegistrationErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishRegistrationError =
  FinishRegistrationErrors[keyof FinishRegistrationErrors];

export type FinishAuthenticationData = {
  body: AuthReq;
  path: {
    auth_id: string;
  };
  query?: never;
  url: '/api/auth/passkey/finish_authentication/{auth_id}';
};

export type FinishAuthenticationErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishAuthenticationError =
  FinishAuthenticationErrors[keyof FinishAuthenticationErrors];

export type FinishSpecialAccessData = {
  body: unknown;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/finish_special_access';
};

export type FinishSpecialAccessErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishSpecialAccessError =
  FinishSpecialAccessErrors[keyof FinishSpecialAccessErrors];

export type StartRegistrationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/start_registration';
};

export type StartRegistrationErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartRegistrationResponses = {
  200: unknown;
};

export type StartAuthenticationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/start_authentication';
};

export type StartAuthenticationErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartAuthenticationResponses = {
  200: AuthStartRes;
};

export type StartAuthenticationResponse =
  StartAuthenticationResponses[keyof StartAuthenticationResponses];

export type StartSpecialAccessData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/start_special_access';
};

export type StartSpecialAccessErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartSpecialAccessResponses = {
  200: unknown;
};

export type ListPasskeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/list';
};

export type ListPasskeysErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListPasskeysResponses = {
  200: Array<PasskeyInfo>;
};

export type ListPasskeysResponse =
  ListPasskeysResponses[keyof ListPasskeysResponses];

export type RemovePasskeyData = {
  body: PasskeyRemove;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/remove';
};

export type RemovePasskeyErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RemovePasskeyError = RemovePasskeyErrors[keyof RemovePasskeyErrors];

export type RemovePasskeyResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type EditPasskeyNameData = {
  body: PasskeyEdit;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/edit_name';
};

export type EditPasskeyNameErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditPasskeyNameError =
  EditPasskeyNameErrors[keyof EditPasskeyNameErrors];

export type EditPasskeyNameResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type PasswordAuthenticateData = {
  body: LoginReq;
  path?: never;
  query?: never;
  url: '/api/auth/password/authenticate';
};

export type PasswordAuthenticateErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type PasswordAuthenticateError =
  PasswordAuthenticateErrors[keyof PasswordAuthenticateErrors];

export type PasswordSpecialAccessData = {
  body: SpecialAccess;
  path?: never;
  query?: never;
  url: '/api/auth/password/special_access';
};

export type PasswordSpecialAccessErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type PasswordSpecialAccessError =
  PasswordSpecialAccessErrors[keyof PasswordSpecialAccessErrors];

export type KeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/password/key';
};

export type KeyResponses = {
  200: KeyRes;
};

export type KeyResponse = KeyResponses[keyof KeyResponses];

export type ChangePasswordData = {
  body: PasswordChange;
  path?: never;
  query?: never;
  url: '/api/auth/password/change';
};

export type ChangePasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ChangePasswordError =
  ChangePasswordErrors[keyof ChangePasswordErrors];

export type TotpConfirmData = {
  body: TotpConfirmReq;
  path?: never;
  query?: never;
  url: '/api/auth/totp/confirm';
};

export type TotpConfirmErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TotpConfirmError = TotpConfirmErrors[keyof TotpConfirmErrors];

export type TotpStartSetupData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/totp/start_setup';
};

export type TotpStartSetupErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TotpStartSetupResponses = {
  200: TotpSetupRes;
};

export type TotpStartSetupResponse =
  TotpStartSetupResponses[keyof TotpStartSetupResponses];

export type TotpFinishSetupData = {
  body: TotpReq;
  path?: never;
  query?: never;
  url: '/api/auth/totp/finish_setup';
};

export type TotpFinishSetupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TotpFinishSetupError =
  TotpFinishSetupErrors[keyof TotpFinishSetupErrors];

export type TotpRemoveData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/totp/remove';
};

export type TotpRemoveErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/config';
};

export type AuthConfigErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthConfigResponses = {
  200: AuthConfig;
};

export type AuthConfigResponse = AuthConfigResponses[keyof AuthConfigResponses];

export type RequestAppCodeData = {
  body: CodeReq;
  path?: never;
  query?: never;
  url: '/api/auth/app/code';
};

export type RequestAppCodeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RequestAppCodeError =
  RequestAppCodeErrors[keyof RequestAppCodeErrors];

export type RequestAppCodeResponses = {
  200: CodeRes;
};

export type RequestAppCodeResponse =
  RequestAppCodeResponses[keyof RequestAppCodeResponses];

export type ExchangeAppCodeData = {
  body: ExchangeCodeReq;
  path?: never;
  query?: never;
  url: '/api/auth/app/exchange';
};

export type ExchangeAppCodeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ExchangeAppCodeError =
  ExchangeAppCodeErrors[keyof ExchangeAppCodeErrors];

export type RetrieveAppTokenData = {
  body: RetrieveTokenReq;
  path?: never;
  query?: never;
  url: '/api/auth/app/retrieve_token';
};

export type RetrieveAppTokenErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RetrieveAppTokenError =
  RetrieveAppTokenErrors[keyof RetrieveAppTokenErrors];

export type TestTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/test_token';
};

export type RefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/refresh_token';
};

export type RefreshTokenErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserAvatarData = {
  body: UserAvatarResetRequest;
  path?: never;
  query?: never;
  url: '/api/user/management/avatar';
};

export type ResetUserAvatarErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserAvatarError =
  ResetUserAvatarErrors[keyof ResetUserAvatarErrors];

export type ResetUserAvatarResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type DeleteUserData = {
  body: DeleteUserRequest;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type DeleteUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type ListUsersErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersResponses = {
  200: Array<UserListInfo>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUser;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type CreateUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  200: CreateUserResponse;
};

export type CreateUserResponse2 =
  CreateUserResponses[keyof CreateUserResponses];

export type EditUserData = {
  body: UserEditReq;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type EditUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditUserError = EditUserErrors[keyof EditUserErrors];

export type EditUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UserInfoData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/user/management/{uuid}';
};

export type UserInfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UserInfoResponses = {
  200: DetailUserInfo;
};

export type UserInfoResponse = UserInfoResponses[keyof UserInfoResponses];

export type MailActiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management/mail';
};

export type MailActiveErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type MailActiveResponses = {
  200: MailActiveResponse;
};

export type MailActiveResponse2 =
  MailActiveResponses[keyof MailActiveResponses];

export type ListGroupsSimpleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management/groups';
};

export type ListGroupsSimpleErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsSimpleResponses = {
  200: Array<SimpleGroupInfo>;
};

export type ListGroupsSimpleResponse =
  ListGroupsSimpleResponses[keyof ListGroupsSimpleResponses];

export type ResetUserPasswordData = {
  body: ResetUserPassword;
  path?: never;
  query?: never;
  url: '/api/user/management/password';
};

export type ResetUserPasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserPasswordError =
  ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ChangeUserEmailData = {
  body: ChangeUserEmail;
  path?: never;
  query?: never;
  url: '/api/user/management/email';
};

export type ChangeUserEmailErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ChangeUserEmailError =
  ChangeUserEmailErrors[keyof ChangeUserEmailErrors];

export type ChangeUserEmailResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ConvertOidcUserData = {
  body: ResetUserPassword;
  path?: never;
  query?: never;
  url: '/api/user/management/convert-oidc';
};

export type ConvertOidcUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ConvertOidcUserError =
  ConvertOidcUserErrors[keyof ConvertOidcUserErrors];

export type ConvertOidcUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdatePasswordData = {
  body: PasswordUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/password';
};

export type UpdatePasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdatePasswordError =
  UpdatePasswordErrors[keyof UpdatePasswordErrors];

export type UpdatePasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type StartEmailChangeData = {
  body: EmailChange;
  path?: never;
  query?: never;
  url: '/api/user/account/email_change_start';
};

export type StartEmailChangeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartEmailChangeError =
  StartEmailChangeErrors[keyof StartEmailChangeErrors];

export type StartEmailChangeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdateAccountData = {
  body: AccountUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/update';
};

export type UpdateAccountErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ConfirmEmailChangeData = {
  body: EmailChangeConfirm;
  path?: never;
  query?: never;
  url: '/api/user/account/email_change_confirm';
};

export type ConfirmEmailChangeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ConfirmEmailChangeError =
  ConfirmEmailChangeErrors[keyof ConfirmEmailChangeErrors];

export type ConfirmEmailChangeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdateAvatarData = {
  body: AvatarUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/avatar';
};

export type UpdateAvatarErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdateAvatarError = UpdateAvatarErrors[keyof UpdateAvatarErrors];

export type UpdateAvatarResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/account/sessions';
};

export type ListSessionsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListSessionsResponses = {
  200: Array<SessionInfo>;
};

export type ListSessionsResponse =
  ListSessionsResponses[keyof ListSessionsResponses];

export type RevokeSessionData = {
  body: RevokeSessionReq;
  path?: never;
  query?: never;
  url: '/api/user/account/sessions';
};

export type RevokeSessionErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RevokeSessionError = RevokeSessionErrors[keyof RevokeSessionErrors];

export type InfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/info';
};

export type InfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoResponses = {
  200: UserInfo;
};

export type InfoResponse = InfoResponses[keyof InfoResponses];

export type AvatarByIdData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/user/info/avatar/{uuid}';
};

export type AvatarByIdErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AvatarByIdResponses = {
  /**
   * byte stream
   */
  200: Blob | File;
};

export type AvatarByIdResponse = AvatarByIdResponses[keyof AvatarByIdResponses];

export type GetMailSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/mail';
};

export type GetMailSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetMailSettingsResponses = {
  200: MailSettingsResponse;
};

export type GetMailSettingsResponse =
  GetMailSettingsResponses[keyof GetMailSettingsResponses];

export type SaveMailSettingsData = {
  body: MailSettings;
  path?: never;
  query?: never;
  url: '/api/settings/mail';
};

export type SaveMailSettingsErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SaveMailSettingsError =
  SaveMailSettingsErrors[keyof SaveMailSettingsErrors];

export type SaveMailSettingsResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type AccountSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/account';
};

export type AccountSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AccountSettingsResponses = {
  200: SettingsInfo;
};

export type AccountSettingsResponse =
  AccountSettingsResponses[keyof AccountSettingsResponses];

export type SaveAccountSettingsData = {
  body: SettingsInfo;
  path?: never;
  query?: never;
  url: '/api/settings/account';
};

export type SaveAccountSettingsErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SaveAccountSettingsError =
  SaveAccountSettingsErrors[keyof SaveAccountSettingsErrors];

export type SaveAccountSettingsResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type SendResetLinkData = {
  body: ResetRequest;
  path?: never;
  query?: never;
  url: '/api/mail/reset/send';
};

export type SendResetLinkErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
};

export type SendResetLinkError = SendResetLinkErrors[keyof SendResetLinkErrors];

export type SendResetLinkResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ResetPasswordData = {
  body: ResetPasswordPayload;
  path?: never;
  query?: never;
  url: '/api/mail/reset/confirm';
};

export type ResetPasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type TestMailData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/mail/test';
};

export type TestMailErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestMailResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type DeleteGroupData = {
  body: DeleteGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type DeleteGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteGroupError = DeleteGroupErrors[keyof DeleteGroupErrors];

export type DeleteGroupResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListGroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type ListGroupsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsResponses = {
  200: ListGroupResponse;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
  body: CreateGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type CreateGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
  200: GroupCreateResponse;
};

export type CreateGroupResponse =
  CreateGroupResponses[keyof CreateGroupResponses];

export type EditGroupData = {
  body: EditGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type EditGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditGroupError = EditGroupErrors[keyof EditGroupErrors];

export type EditGroupResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GroupInfoData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/group/{uuid}';
};

export type GroupInfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GroupInfoResponses = {
  200: GroupDetailsResponse;
};

export type GroupInfoResponse = GroupInfoResponses[keyof GroupInfoResponses];

export type ListUsersSimpleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/group/users';
};

export type ListUsersSimpleErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersSimpleResponses = {
  200: Array<SimpleUserInfo>;
};

export type ListUsersSimpleResponse =
  ListUsersSimpleResponses[keyof ListUsersSimpleResponses];

export type ListApodData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/services/apod';
};

export type ListApodErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListApodResponses = {
  200: Array<ApodInfo>;
};

export type ListApodResponse = ListApodResponses[keyof ListApodResponses];

export type SetGoodApodData = {
  body: SetGoodReq;
  path?: never;
  query?: never;
  url: '/api/services/apod';
};

export type SetGoodApodErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SetGoodApodError = SetGoodApodErrors[keyof SetGoodApodErrors];

export type SetGoodApodResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GetApodImageInfoData = {
  body: GetInfoReq;
  path?: never;
  query?: never;
  url: '/api/services/apod/get_image_info';
};

export type GetApodImageInfoErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetApodImageInfoError =
  GetApodImageInfoErrors[keyof GetApodImageInfoErrors];

export type GetApodImageInfoResponses = {
  200: GetInfoRes;
};

export type GetApodImageInfoResponse =
  GetApodImageInfoResponses[keyof GetApodImageInfoResponses];

export type GetApodImageData = {
  body?: never;
  path?: never;
  query: {
    date: Date;
    preview?: boolean;
  };
  url: '/api/services/apod/get_image';
};

export type GetApodImageErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthorizeConfirmData = {
  body?: never;
  path?: never;
  query: {
    allow?: boolean;
    code: string;
  };
  url: '/api/oauth/authorize_confirm';
};

export type AuthorizeConfirmErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthorizeConfirmResponses = {
  200: AuthRes;
};

export type AuthorizeConfirmResponse =
  AuthorizeConfirmResponses[keyof AuthorizeConfirmResponses];

export type DeleteOauthClientData = {
  body: DeleteClientRequest;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type DeleteOauthClientErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteOauthClientError =
  DeleteOauthClientErrors[keyof DeleteOauthClientErrors];

export type DeleteOauthClientResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListOauthClientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type ListOauthClientsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListOauthClientsResponses = {
  200: Array<OAuthClientInfo>;
};

export type ListOauthClientsResponse =
  ListOauthClientsResponses[keyof ListOauthClientsResponses];

export type CreateOauthClientData = {
  body: ClientCreate;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type CreateOauthClientErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateOauthClientError =
  CreateOauthClientErrors[keyof CreateOauthClientErrors];

export type CreateOauthClientResponses = {
  200: ClientCreateRes;
};

export type CreateOauthClientResponse =
  CreateOauthClientResponses[keyof CreateOauthClientResponses];

export type EditOauthClientData = {
  body: OAuthClientEditReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type EditOauthClientErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditOauthClientError =
  EditOauthClientErrors[keyof EditOauthClientErrors];

export type EditOauthClientResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoOauthClientData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/client/{uuid}';
};

export type InfoOauthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoOauthClientResponses = {
  200: OAuthClientInfo;
};

export type InfoOauthClientResponse =
  InfoOauthClientResponses[keyof InfoOauthClientResponses];

export type RegenerateSecretOauthClientData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/client/{uuid}';
};

export type RegenerateSecretOauthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RegenerateSecretOauthClientResponses = {
  200: OAuthRegenerateResponse;
};

export type RegenerateSecretOauthClientResponse =
  RegenerateSecretOauthClientResponses[keyof RegenerateSecretOauthClientResponses];

export type SiteUrlData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/site_url';
};

export type SiteUrlErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SiteUrlResponses = {
  200: SiteUrlResponse;
};

export type SiteUrlResponse2 = SiteUrlResponses[keyof SiteUrlResponses];

export type ListGroupsOAuthClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/groups';
};

export type ListGroupsOAuthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsOAuthClientResponses = {
  200: Array<SimpleGroupInfo>;
};

export type ListGroupsOAuthClientResponse =
  ListGroupsOAuthClientResponses[keyof ListGroupsOAuthClientResponses];

export type ListUsersOAuthClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/users';
};

export type ListUsersOAuthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersOAuthClientResponses = {
  200: Array<SimpleUserInfo>;
};

export type ListUsersOAuthClientResponse =
  ListUsersOAuthClientResponses[keyof ListUsersOAuthClientResponses];

export type ListScopesOAuthClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/scopes';
};

export type ListScopesOAuthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListScopesOAuthClientResponses = {
  200: Array<SimpleOAuthScopeInfo>;
};

export type ListScopesOAuthClientResponse =
  ListScopesOAuthClientResponses[keyof ListScopesOAuthClientResponses];

export type DeleteOAuthScopeData = {
  body: DeleteReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type DeleteOAuthScopeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteOAuthScopeError =
  DeleteOAuthScopeErrors[keyof DeleteOAuthScopeErrors];

export type DeleteOAuthScopeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListOAuthScopesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type ListOAuthScopesErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListOAuthScopesResponses = {
  200: Array<OAuthScopeInfo>;
};

export type ListOAuthScopesResponse =
  ListOAuthScopesResponses[keyof ListOAuthScopesResponses];

export type CreateOAuthScopeData = {
  body: CreateReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type CreateOAuthScopeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateOAuthScopeError =
  CreateOAuthScopeErrors[keyof CreateOAuthScopeErrors];

export type CreateOAuthScopeResponses = {
  200: CreateRes;
};

export type CreateOAuthScopeResponse =
  CreateOAuthScopeResponses[keyof CreateOAuthScopeResponses];

export type EditOAuthScopeData = {
  body: OAuthScopeEditReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type EditOAuthScopeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditOAuthScopeError =
  EditOAuthScopeErrors[keyof EditOAuthScopeErrors];

export type EditOAuthScopeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoOAuthScopeData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/scope/{uuid}';
};

export type InfoOAuthScopeErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoOAuthScopeResponses = {
  200: OAuthScopeInfo;
};

export type InfoOAuthScopeResponse =
  InfoOAuthScopeResponses[keyof InfoOAuthScopeResponses];

export type ListPoliciesOAuthScopeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope/policies';
};

export type ListPoliciesOAuthScopeErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListPoliciesOAuthScopeResponses = {
  200: Array<SimpleOAuthPolicyInfo>;
};

export type ListPoliciesOAuthScopeResponse =
  ListPoliciesOAuthScopeResponses[keyof ListPoliciesOAuthScopeResponses];

export type DeleteOAuthPolicyData = {
  body: DeleteReq2;
  path?: never;
  query?: never;
  url: '/api/oauth_management/policy';
};

export type DeleteOAuthPolicyErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteOAuthPolicyError =
  DeleteOAuthPolicyErrors[keyof DeleteOAuthPolicyErrors];

export type DeleteOAuthPolicyResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListOAuthPoliciesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/policy';
};

export type ListOAuthPoliciesErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListOAuthPoliciesResponses = {
  200: Array<OAuthPolicyInfo>;
};

export type ListOAuthPoliciesResponse =
  ListOAuthPoliciesResponses[keyof ListOAuthPoliciesResponses];

export type CreateOAuthPolicyData = {
  body: CreateReq2;
  path?: never;
  query?: never;
  url: '/api/oauth_management/policy';
};

export type CreateOAuthPolicyErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateOAuthPolicyError =
  CreateOAuthPolicyErrors[keyof CreateOAuthPolicyErrors];

export type CreateOAuthPolicyResponses = {
  200: CreateRes2;
};

export type CreateOAuthPolicyResponse =
  CreateOAuthPolicyResponses[keyof CreateOAuthPolicyResponses];

export type EditOAuthPolicyData = {
  body: OAuthPolicyInfo;
  path?: never;
  query?: never;
  url: '/api/oauth_management/policy';
};

export type EditOAuthPolicyErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditOAuthPolicyError =
  EditOAuthPolicyErrors[keyof EditOAuthPolicyErrors];

export type EditOAuthPolicyResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoOAuthPolicyData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/policy/{uuid}';
};

export type InfoOAuthPolicyErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoOAuthPolicyResponses = {
  200: OAuthPolicyInfo;
};

export type InfoOAuthPolicyResponse =
  InfoOAuthPolicyResponses[keyof InfoOAuthPolicyResponses];

export type ListGroupsOAuthPolicyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/policy/groups';
};

export type ListGroupsOAuthPolicyErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsOAuthPolicyResponses = {
  200: Array<SimpleGroupInfo>;
};

export type ListGroupsOAuthPolicyResponse =
  ListGroupsOAuthPolicyResponses[keyof ListGroupsOAuthPolicyResponses];

export type DeleteNoteData = {
  body: NoteDeleteReq;
  path?: never;
  query?: never;
  url: '/api/notes/management';
};

export type DeleteNoteErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteNoteError = DeleteNoteErrors[keyof DeleteNoteErrors];

export type DeleteNoteResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListNotesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notes/management';
};

export type ListNotesErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListNotesResponses = {
  200: Array<NoteInfo>;
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type CreateNoteData = {
  body: NoteCreateReq;
  path?: never;
  query?: never;
  url: '/api/notes/management';
};

export type CreateNoteErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateNoteError = CreateNoteErrors[keyof CreateNoteErrors];

export type CreateNoteResponses = {
  200: NoteCreateRes;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type EditNoteData = {
  body: NoteEditReq;
  path?: never;
  query?: never;
  url: '/api/notes/management';
};

export type EditNoteErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditNoteError = EditNoteErrors[keyof EditNoteErrors];

export type EditNoteResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoNoteData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/notes/management/{uuid}';
};

export type InfoNoteErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoNoteResponses = {
  200: NoteInfo;
};

export type InfoNoteResponse = InfoNoteResponses[keyof InfoNoteResponses];

export type InfoNoteShareData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/notes/management/{uuid}/public';
};

export type InfoNoteShareErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoNoteShareResponses = {
  200: NoteInfoPublic;
};

export type InfoNoteShareResponse =
  InfoNoteShareResponses[keyof InfoNoteShareResponses];

export type ListUsersNoteData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notes/management/users';
};

export type ListUsersNoteErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersNoteResponses = {
  200: Array<SimpleUserInfo>;
};

export type ListUsersNoteResponse =
  ListUsersNoteResponses[keyof ListUsersNoteResponses];

export type ShareNoteData = {
  body: NoteShareReq;
  path?: never;
  query?: never;
  url: '/api/notes/management/share';
};

export type ShareNoteErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ShareNoteError = ShareNoteErrors[keyof ShareNoteErrors];

export type ShareNoteResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ShareNotePublicData = {
  body: NotePublicShareReq;
  path?: never;
  query?: never;
  url: '/api/notes/management/share/public';
};

export type ShareNotePublicErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ShareNotePublicError =
  ShareNotePublicErrors[keyof ShareNotePublicErrors];

export type ShareNotePublicResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type TransferNoteData = {
  body: NoteTransferReq;
  path?: never;
  query?: never;
  url: '/api/notes/management/transfer';
};

export type TransferNoteErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TransferNoteError = TransferNoteErrors[keyof TransferNoteErrors];

export type TransferNoteResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type NotesConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notes/management/config';
};

export type NotesConfigErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type NotesConfigResponses = {
  200: NotesConfigRes;
};

export type NotesConfigResponse =
  NotesConfigResponses[keyof NotesConfigResponses];

export type ListNoteSnapshotsData = {
  body?: never;
  path: {
    note_uuid: string;
  };
  query?: never;
  url: '/api/notes/snapshots/{note_uuid}';
};

export type ListNoteSnapshotsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListNoteSnapshotsResponses = {
  200: Array<NoteSnapshotInfo>;
};

export type ListNoteSnapshotsResponse =
  ListNoteSnapshotsResponses[keyof ListNoteSnapshotsResponses];

export type DeleteNoteSnapshotData = {
  body: NoteSnapshotIdReq;
  path?: never;
  query?: never;
  url: '/api/notes/snapshots';
};

export type DeleteNoteSnapshotErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteNoteSnapshotError =
  DeleteNoteSnapshotErrors[keyof DeleteNoteSnapshotErrors];

export type DeleteNoteSnapshotResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type RestoreNoteSnapshotData = {
  body: NoteSnapshotIdReq;
  path?: never;
  query?: never;
  url: '/api/notes/snapshots/restore';
};

export type RestoreNoteSnapshotErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RestoreNoteSnapshotError =
  RestoreNoteSnapshotErrors[keyof RestoreNoteSnapshotErrors];

export type RestoreNoteSnapshotResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoNoteSnapshotData = {
  body?: never;
  path: {
    snapshot_id: string;
  };
  query?: never;
  url: '/api/notes/snapshots/{snapshot_id}/info';
};

export type InfoNoteSnapshotErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoNoteSnapshotResponses = {
  200: NoteSnapshotDetail;
};

export type InfoNoteSnapshotResponse =
  InfoNoteSnapshotResponses[keyof InfoNoteSnapshotResponses];

export type GetNoteSnapshotContentData = {
  body?: never;
  path: {
    snapshot_id: string;
  };
  query?: never;
  url: '/api/notes/snapshots/{snapshot_id}/content';
};

export type GetNoteSnapshotContentErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};
