// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5175' | (string & {});
};

export type AccountUpdate = {
  username: string;
};

export type AuthConfig = {
  mail_enabled: boolean;
};

export type AuthStartRes = {
  id: string;
};

export type AvatarPath = {
  uuid: string;
};

export type AvatarUpdate = {
  avatar: string;
};

export type ChangeUserEmail = {
  new_email: string;
  uuid: string;
};

export type ClientCreate = {
  confidential: boolean;
  name: string;
  redirect_uri: string;
  scope: Scope;
};

export type ClientCreateRes = {
  client_id: string;
  client_secret: string;
};

export type CreateGroupRequest = {
  name: string;
};

export type CreateReq = {
  name: string;
  policies: Array<string>;
  scope: string;
};

export type CreateRes = {
  uuid: string;
};

export type CreateUser = {
  email: string;
  name: string;
  password?: string | null;
};

export type CreateUserResponse = {
  uuid: string;
};

export type DeleteClientRequest = {
  client_id: string;
};

export type DeleteGroupRequest = {
  uuid: string;
};

export type DeleteReq = {
  uuid: string;
};

export type DeleteUserRequest = {
  uuid: string;
};

export type DetailUserInfo = {
  email: string;
  groups: Array<SimpleGroupInfo>;
  name: string;
  permissions: Array<string>;
  uuid: string;
};

export type EditGroupRequest = {
  name: string;
  permissions: Array<string>;
  users: Array<string>;
  uuid: string;
};

export type EmailChange = {
  new_email: string;
};

export type EmailChangeConfirm = {
  new_code: string;
  old_code: string;
};

export type FinishAuthPath = {
  auth_id: string;
};

export type GetInfoRes = {
  title: string;
  user?: SimpleUserInfo | null;
};

export type GetReq = {
  date: Date;
};

export type GetRes = {
  image: string;
};

export type GroupCreateResponse = {
  uuid: string;
};

export type GroupDetails = {
  id: string;
  name: string;
  permissions: Array<string>;
  users: Array<SimpleUserInfo>;
};

export type GroupDetailsResponse = {
  admin_group: string;
  group: GroupDetails;
};

export type GroupInfo = {
  id: string;
  name: string;
  permissions: Array<string>;
  users: Array<SimpleUserInfo>;
};

export type GroupViewPath = {
  uuid: string;
};

export type IsSetupResponse = {
  db_backend: string;
  is_setup: boolean;
  storage_backend: string;
};

export type KeyRes = {
  key: string;
};

export type ListGroupResponse = {
  admin_group?: string | null;
  groups: Array<GroupInfo>;
};

export type ListRes = {
  date: Date;
  image: string;
  title: string;
  user: SimpleUserInfo;
};

export type LoginReq = {
  email: string;
  password: string;
};

export type MailActiveResponse = {
  active: boolean;
};

export type MailSettings = {
  smtp_enabled?: boolean;
  smtp_from_address?: string | null;
  smtp_from_name?: string | null;
  smtp_password?: string | null;
  smtp_port?: number | null;
  smtp_server?: string | null;
  smtp_use_tls?: boolean | null;
  smtp_username?: string | null;
};

export type MailSettingsResponse = {
  from_env: Array<string>;
  settings: MailSettings;
};

export type OAuthClientEditReq = {
  additional_redirect_uris: Array<string>;
  client_id: string;
  group_access: Array<string>;
  name: string;
  redirect_uri: string;
  scope: Scope;
  user_access: Array<string>;
};

export type OAuthClientInfo = {
  additional_redirect_uris: Array<string>;
  client_id: string;
  confidential: boolean;
  default_scope: Scope;
  group_access: Array<SimpleGroupInfo>;
  name: string;
  redirect_uri: string;
  user_access: Array<SimpleUserInfo>;
};

export type OAuthClientPath = {
  uuid: string;
};

export type OAuthRegenerateResponse = {
  secret: string;
};

export type OAuthScopeEditReq = {
  name: string;
  policies: Array<string>;
  scope: string;
  uuid: string;
};

export type OAuthScopeInfo = {
  name: string;
  policies: Array<SimpleOAuthPolicyInfo>;
  scope: string;
  uuid: string;
};

export type OAuthScopePath = {
  uuid: string;
};

export type PasskeyEdit = {
  name: string;
  old_name: string;
};

export type PasskeyInfo = {
  created: Date;
  name: string;
  used: Date;
};

export type PasskeyRemove = {
  name: string;
};

export type PasswordChange = {
  password: string;
  password_confirm: string;
};

export type PasswordUpdate = {
  new_password: string;
  old_password: string;
};

export type RegFinishReq = {
  name: string;
};

export type ResetPasswordPayload = {
  new_password: string;
  token: string;
};

export type ResetRequest = {
  email: string;
};

export type ResetUserPassword = {
  new_password: string;
  uuid: string;
};

export type Scope = Array<string>;

export type SetGoodReq = {
  date: Date;
  good: boolean;
};

export type SettingsInfo = {
  o_auth_instant_confirm: boolean;
};

export type SetupPayload = {
  admin_email: string;
  admin_password: string;
  admin_username: string;
};

export type SimpleGroupInfo = {
  name: string;
  uuid: string;
};

export type SimpleOAuthPolicyInfo = {
  name: string;
  uuid: string;
};

export type SimpleOAuthScopeInfo = {
  name: string;
  uuid: string;
};

export type SimpleUserInfo = {
  id: string;
  name: string;
};

export type SiteUrlResponse = {
  url: string;
};

export type SpecialAccess = {
  password: string;
};

export type TotpReq = {
  code: string;
};

export type TotpSetupRes = {
  code: string;
  qr: string;
};

export type UserAvatarResetRequest = {
  uuid: string;
};

export type UserEditReq = {
  groups: Array<string>;
  name: string;
  uuid: string;
};

export type UserInfo = {
  email: string;
  name: string;
  permissions: Array<string>;
  totp_enabled: boolean;
  uuid: string;
};

export type UserListInfo = {
  email: string;
  groups: Array<SimpleGroupInfo>;
  name: string;
  uuid: string;
};

export type UserViewPath = {
  uuid: string;
};

export type IsSetupData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/setup';
};

export type IsSetupErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type IsSetupResponses = {
  200: IsSetupResponse;
};

export type IsSetupResponse2 = IsSetupResponses[keyof IsSetupResponses];

export type CompleteSetupData = {
  body: SetupPayload;
  path?: never;
  query?: never;
  url: '/api/setup';
};

export type CompleteSetupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CompleteSetupError = CompleteSetupErrors[keyof CompleteSetupErrors];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/test_token';
};

export type FinishRegistrationData = {
  body: RegFinishReq;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/finish_registration';
};

export type FinishRegistrationErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishRegistrationError =
  FinishRegistrationErrors[keyof FinishRegistrationErrors];

export type FinishAuthenticationData = {
  body: unknown;
  path: {
    auth_id: string;
  };
  query?: never;
  url: '/api/auth/passkey/finish_authentication/{auth_id}';
};

export type FinishAuthenticationErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishAuthenticationError =
  FinishAuthenticationErrors[keyof FinishAuthenticationErrors];

export type FinishSpecialAccessData = {
  body: unknown;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/finish_special_access';
};

export type FinishSpecialAccessErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type FinishSpecialAccessError =
  FinishSpecialAccessErrors[keyof FinishSpecialAccessErrors];

export type StartRegistrationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/start_registration';
};

export type StartRegistrationErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartRegistrationResponses = {
  200: unknown;
};

export type StartAuthenticationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/start_authentication';
};

export type StartAuthenticationErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartAuthenticationResponses = {
  200: AuthStartRes;
};

export type StartAuthenticationResponse =
  StartAuthenticationResponses[keyof StartAuthenticationResponses];

export type StartSpecialAccessData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/start_special_access';
};

export type StartSpecialAccessErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartSpecialAccessResponses = {
  200: unknown;
};

export type ListPasskeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/list';
};

export type ListPasskeysErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListPasskeysResponses = {
  200: Array<PasskeyInfo>;
};

export type ListPasskeysResponse =
  ListPasskeysResponses[keyof ListPasskeysResponses];

export type RemovePasskeyData = {
  body: PasskeyRemove;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/remove';
};

export type RemovePasskeyErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RemovePasskeyError = RemovePasskeyErrors[keyof RemovePasskeyErrors];

export type RemovePasskeyResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type EditPasskeyNameData = {
  body: PasskeyEdit;
  path?: never;
  query?: never;
  url: '/api/auth/passkey/edit_name';
};

export type EditPasskeyNameErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditPasskeyNameError =
  EditPasskeyNameErrors[keyof EditPasskeyNameErrors];

export type EditPasskeyNameResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type PasswordAuthenticateData = {
  body: LoginReq;
  path?: never;
  query?: never;
  url: '/api/auth/password/authenticate';
};

export type PasswordAuthenticateErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type PasswordAuthenticateError =
  PasswordAuthenticateErrors[keyof PasswordAuthenticateErrors];

export type PasswordSpecialAccessData = {
  body: SpecialAccess;
  path?: never;
  query?: never;
  url: '/api/auth/password/special_access';
};

export type PasswordSpecialAccessErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type PasswordSpecialAccessError =
  PasswordSpecialAccessErrors[keyof PasswordSpecialAccessErrors];

export type KeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/password/key';
};

export type KeyResponses = {
  200: KeyRes;
};

export type KeyResponse = KeyResponses[keyof KeyResponses];

export type ChangePasswordData = {
  body: PasswordChange;
  path?: never;
  query?: never;
  url: '/api/auth/password/change';
};

export type ChangePasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ChangePasswordError =
  ChangePasswordErrors[keyof ChangePasswordErrors];

export type TotpConfirmData = {
  body: TotpReq;
  path?: never;
  query?: never;
  url: '/api/auth/totp/confirm';
};

export type TotpConfirmErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TotpConfirmError = TotpConfirmErrors[keyof TotpConfirmErrors];

export type TotpStartSetupData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/totp/start_setup';
};

export type TotpStartSetupErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TotpStartSetupResponses = {
  200: TotpSetupRes;
};

export type TotpStartSetupResponse =
  TotpStartSetupResponses[keyof TotpStartSetupResponses];

export type TotpFinishSetupData = {
  body: TotpReq;
  path?: never;
  query?: never;
  url: '/api/auth/totp/finish_setup';
};

export type TotpFinishSetupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TotpFinishSetupError =
  TotpFinishSetupErrors[keyof TotpFinishSetupErrors];

export type TotpRemoveData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/totp/remove';
};

export type TotpRemoveErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/config';
};

export type AuthConfigErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthConfigResponses = {
  200: AuthConfig;
};

export type AuthConfigResponse = AuthConfigResponses[keyof AuthConfigResponses];

export type ResetUserAvatarData = {
  body: UserAvatarResetRequest;
  path?: never;
  query?: never;
  url: '/api/user/management/avatar';
};

export type ResetUserAvatarErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserAvatarError =
  ResetUserAvatarErrors[keyof ResetUserAvatarErrors];

export type ResetUserAvatarResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type DeleteUserData = {
  body: DeleteUserRequest;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type DeleteUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type ListUsersErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersResponses = {
  200: Array<UserListInfo>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUser;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type CreateUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  200: CreateUserResponse;
};

export type CreateUserResponse2 =
  CreateUserResponses[keyof CreateUserResponses];

export type EditUserData = {
  body: UserEditReq;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type EditUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditUserError = EditUserErrors[keyof EditUserErrors];

export type EditUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UserInfoData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/user/management/{uuid}';
};

export type UserInfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UserInfoResponses = {
  200: DetailUserInfo;
};

export type UserInfoResponse = UserInfoResponses[keyof UserInfoResponses];

export type MailActiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management/mail';
};

export type MailActiveErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type MailActiveResponses = {
  200: MailActiveResponse;
};

export type MailActiveResponse2 =
  MailActiveResponses[keyof MailActiveResponses];

export type ListGroupsSimpleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management/groups';
};

export type ListGroupsSimpleErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsSimpleResponses = {
  200: Array<SimpleGroupInfo>;
};

export type ListGroupsSimpleResponse =
  ListGroupsSimpleResponses[keyof ListGroupsSimpleResponses];

export type ResetUserPasswordData = {
  body: ResetUserPassword;
  path?: never;
  query?: never;
  url: '/api/user/management/password';
};

export type ResetUserPasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserPasswordError =
  ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ChangeUserEmailData = {
  body: ChangeUserEmail;
  path?: never;
  query?: never;
  url: '/api/user/management/email';
};

export type ChangeUserEmailErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ChangeUserEmailError =
  ChangeUserEmailErrors[keyof ChangeUserEmailErrors];

export type ChangeUserEmailResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdateAvatarData = {
  body: AvatarUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/avatar';
};

export type UpdateAvatarErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdateAvatarError = UpdateAvatarErrors[keyof UpdateAvatarErrors];

export type UpdateAvatarResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdatePasswordData = {
  body: PasswordUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/password';
};

export type UpdatePasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdatePasswordError =
  UpdatePasswordErrors[keyof UpdatePasswordErrors];

export type UpdatePasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type StartEmailChangeData = {
  body: EmailChange;
  path?: never;
  query?: never;
  url: '/api/user/account/email_change_start';
};

export type StartEmailChangeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type StartEmailChangeError =
  StartEmailChangeErrors[keyof StartEmailChangeErrors];

export type StartEmailChangeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdateAccountData = {
  body: AccountUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/update';
};

export type UpdateAccountErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ConfirmEmailChangeData = {
  body: EmailChangeConfirm;
  path?: never;
  query?: never;
  url: '/api/user/account/email_change_confirm';
};

export type ConfirmEmailChangeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ConfirmEmailChangeError =
  ConfirmEmailChangeErrors[keyof ConfirmEmailChangeErrors];

export type ConfirmEmailChangeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/info';
};

export type InfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoResponses = {
  200: UserInfo;
};

export type InfoResponse = InfoResponses[keyof InfoResponses];

export type AvatarByIdData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/user/info/avatar/{uuid}';
};

export type AvatarByIdErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AvatarByIdResponses = {
  /**
   * byte stream
   */
  200: Blob | File;
};

export type AvatarByIdResponse = AvatarByIdResponses[keyof AvatarByIdResponses];

export type GetMailSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/mail';
};

export type GetMailSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetMailSettingsResponses = {
  200: MailSettingsResponse;
};

export type GetMailSettingsResponse =
  GetMailSettingsResponses[keyof GetMailSettingsResponses];

export type SaveMailSettingsData = {
  body: MailSettings;
  path?: never;
  query?: never;
  url: '/api/settings/mail';
};

export type SaveMailSettingsErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SaveMailSettingsError =
  SaveMailSettingsErrors[keyof SaveMailSettingsErrors];

export type SaveMailSettingsResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type AccountSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/account';
};

export type AccountSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AccountSettingsResponses = {
  200: SettingsInfo;
};

export type AccountSettingsResponse =
  AccountSettingsResponses[keyof AccountSettingsResponses];

export type SaveAccountSettingsData = {
  body: SettingsInfo;
  path?: never;
  query?: never;
  url: '/api/settings/account';
};

export type SaveAccountSettingsErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SaveAccountSettingsError =
  SaveAccountSettingsErrors[keyof SaveAccountSettingsErrors];

export type SaveAccountSettingsResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type SendResetLinkData = {
  body: ResetRequest;
  path?: never;
  query?: never;
  url: '/api/mail/reset/send';
};

export type SendResetLinkErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
};

export type SendResetLinkError = SendResetLinkErrors[keyof SendResetLinkErrors];

export type SendResetLinkResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ResetPasswordData = {
  body: ResetPasswordPayload;
  path?: never;
  query?: never;
  url: '/api/mail/reset/confirm';
};

export type ResetPasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type TestMailData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/mail/test';
};

export type TestMailErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestMailResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type DeleteGroupData = {
  body: DeleteGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type DeleteGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteGroupError = DeleteGroupErrors[keyof DeleteGroupErrors];

export type DeleteGroupResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListGroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type ListGroupsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsResponses = {
  200: ListGroupResponse;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
  body: CreateGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type CreateGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
  200: GroupCreateResponse;
};

export type CreateGroupResponse =
  CreateGroupResponses[keyof CreateGroupResponses];

export type EditGroupData = {
  body: EditGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type EditGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditGroupError = EditGroupErrors[keyof EditGroupErrors];

export type EditGroupResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GroupInfoData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/group/{uuid}';
};

export type GroupInfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GroupInfoResponses = {
  200: GroupDetailsResponse;
};

export type GroupInfoResponse = GroupInfoResponses[keyof GroupInfoResponses];

export type ListUsersSimpleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/group/users';
};

export type ListUsersSimpleErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersSimpleResponses = {
  200: Array<SimpleUserInfo>;
};

export type ListUsersSimpleResponse =
  ListUsersSimpleResponses[keyof ListUsersSimpleResponses];

export type ListApodData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/services/apod';
};

export type ListApodErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListApodResponses = {
  200: Array<ListRes>;
};

export type ListApodResponse = ListApodResponses[keyof ListApodResponses];

export type SetGoodApodData = {
  body: SetGoodReq;
  path?: never;
  query?: never;
  url: '/api/services/apod';
};

export type SetGoodApodErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SetGoodApodError = SetGoodApodErrors[keyof SetGoodApodErrors];

export type SetGoodApodResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GetApodImageInfoData = {
  body: GetReq;
  path?: never;
  query?: never;
  url: '/api/services/apod/get_image_info';
};

export type GetApodImageInfoErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetApodImageInfoError =
  GetApodImageInfoErrors[keyof GetApodImageInfoErrors];

export type GetApodImageInfoResponses = {
  200: GetInfoRes;
};

export type GetApodImageInfoResponse =
  GetApodImageInfoResponses[keyof GetApodImageInfoResponses];

export type GetApodImageData = {
  body: GetReq;
  path?: never;
  query?: never;
  url: '/api/services/apod/get_image';
};

export type GetApodImageErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetApodImageError = GetApodImageErrors[keyof GetApodImageErrors];

export type GetApodImageResponses = {
  200: GetRes;
};

export type GetApodImageResponse =
  GetApodImageResponses[keyof GetApodImageResponses];

export type DeleteOauthClientData = {
  body: DeleteClientRequest;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type DeleteOauthClientErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteOauthClientError =
  DeleteOauthClientErrors[keyof DeleteOauthClientErrors];

export type DeleteOauthClientResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListOauthClientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type ListOauthClientsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListOauthClientsResponses = {
  200: Array<OAuthClientInfo>;
};

export type ListOauthClientsResponse =
  ListOauthClientsResponses[keyof ListOauthClientsResponses];

export type CreateOauthClientData = {
  body: ClientCreate;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type CreateOauthClientErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateOauthClientError =
  CreateOauthClientErrors[keyof CreateOauthClientErrors];

export type CreateOauthClientResponses = {
  200: ClientCreateRes;
};

export type CreateOauthClientResponse =
  CreateOauthClientResponses[keyof CreateOauthClientResponses];

export type EditOauthClientData = {
  body: OAuthClientEditReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client';
};

export type EditOauthClientErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditOauthClientError =
  EditOauthClientErrors[keyof EditOauthClientErrors];

export type EditOauthClientResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoOauthClientData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/client/{uuid}';
};

export type InfoOauthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoOauthClientResponses = {
  200: OAuthClientInfo;
};

export type InfoOauthClientResponse =
  InfoOauthClientResponses[keyof InfoOauthClientResponses];

export type RegenerateSecretOauthClientData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/client/{uuid}';
};

export type RegenerateSecretOauthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type RegenerateSecretOauthClientResponses = {
  200: OAuthRegenerateResponse;
};

export type RegenerateSecretOauthClientResponse =
  RegenerateSecretOauthClientResponses[keyof RegenerateSecretOauthClientResponses];

export type SiteUrlData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/site_url';
};

export type SiteUrlErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SiteUrlResponses = {
  200: SiteUrlResponse;
};

export type SiteUrlResponse2 = SiteUrlResponses[keyof SiteUrlResponses];

export type ListGroupsOAuthClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/groups';
};

export type ListGroupsOAuthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsOAuthClientResponses = {
  200: Array<SimpleGroupInfo>;
};

export type ListGroupsOAuthClientResponse =
  ListGroupsOAuthClientResponses[keyof ListGroupsOAuthClientResponses];

export type ListUsersOAuthClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/users';
};

export type ListUsersOAuthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersOAuthClientResponses = {
  200: Array<SimpleUserInfo>;
};

export type ListUsersOAuthClientResponse =
  ListUsersOAuthClientResponses[keyof ListUsersOAuthClientResponses];

export type ListScopesOAuthClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/client/scopes';
};

export type ListScopesOAuthClientErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListScopesOAuthClientResponses = {
  200: Array<SimpleOAuthScopeInfo>;
};

export type ListScopesOAuthClientResponse =
  ListScopesOAuthClientResponses[keyof ListScopesOAuthClientResponses];

export type DeleteOAuthScopeData = {
  body: DeleteReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type DeleteOAuthScopeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteOAuthScopeError =
  DeleteOAuthScopeErrors[keyof DeleteOAuthScopeErrors];

export type DeleteOAuthScopeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListOAuthScopesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type ListOAuthScopesErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListOAuthScopesResponses = {
  200: Array<OAuthScopeInfo>;
};

export type ListOAuthScopesResponse =
  ListOAuthScopesResponses[keyof ListOAuthScopesResponses];

export type CreateOAuthScopeData = {
  body: CreateReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type CreateOAuthScopeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateOAuthScopeError =
  CreateOAuthScopeErrors[keyof CreateOAuthScopeErrors];

export type CreateOAuthScopeResponses = {
  200: CreateRes;
};

export type CreateOAuthScopeResponse =
  CreateOAuthScopeResponses[keyof CreateOAuthScopeResponses];

export type EditOAuthScopeData = {
  body: OAuthScopeEditReq;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope';
};

export type EditOAuthScopeErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditOAuthScopeError =
  EditOAuthScopeErrors[keyof EditOAuthScopeErrors];

export type EditOAuthScopeResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoOAuthScopeData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/oauth_management/scope/{uuid}';
};

export type InfoOAuthScopeErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoOAuthScopeResponses = {
  200: OAuthScopeInfo;
};

export type InfoOAuthScopeResponse =
  InfoOAuthScopeResponses[keyof InfoOAuthScopeResponses];

export type ListPoliciesOAuthScopeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/oauth_management/scope/policies';
};

export type ListPoliciesOAuthScopeErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListPoliciesOAuthScopeResponses = {
  200: Array<SimpleOAuthPolicyInfo>;
};

export type ListPoliciesOAuthScopeResponse =
  ListPoliciesOAuthScopeResponses[keyof ListPoliciesOAuthScopeResponses];
