[package]
name = "positron-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
dotenv = "0.15.0"
rocket = { version = "0.5.1" ,features = ["json"] }
rocket_cors = "0.6.0"
serde = { version = "1.0.214", features = ["derive"] }
surrealdb = "2.0.4"
webauthn-rs = "0.5.0"
