name: Tests
on:
  pull_request:

jobs:
  backend_test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: clippy,rustfmt

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "backend_test_cache"

      - uses: taiki-e/install-action@nextest
      - name: "Backend Test"
        run: cd backend && cargo nextest run --all-features

      - name: Upload Test Result File
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results-backend
          path: ${{ github.workspace }}/target/nextest/default/junit-backend.xml
          retention-days: 5

  frontend_unit:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: bahmutov/npm-install@v1
      - name: Generate svelte data
        run: |
          echo "BACKEND_URL=http://localhost:8000" > frontend/.env
          cd frontend && npm run sync && cd ..

      - name: Run tests
        run: cd frontend && npm run test:unit -- --reporter junit --reporter default --outputFile test-results-frontend-unit.xml

      - name: Upload Test Result File
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results-frontend-unit
          path: ${{ github.workspace }}/frontend/test-results-frontend-unit.xml
          retention-days: 5

  frontend_e2e:
    name: Frontend E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: bahmutov/npm-install@v1
      - name: Generate svelte data
        run: |
          echo "BACKEND_URL=http://localhost:8000" > frontend/.env
          cd frontend && npm run sync && cd ..

      - name: Install Playwright Browsers
        run: cd frontend && npx playwright install --with-deps && cd ..

      - name: Build Frontend
        run: cd frontend && npm run build && cd ..

      - name: Run tests
        run: cd frontend && npm run test:e2e

      - name: Upload Test Result File
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results-frontend-e2e
          path: ${{ github.workspace }}/frontend/test-results/frontend-e2e.xml
          retention-days: 5

      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-report-frontend-e2e
          path: ${{ github.workspace }}/frontend/playwright-report/
          retention-days: 5

  comment_results:
    name: Comment Results to PR
    runs-on: ubuntu-latest
    if: always()
    needs:
      - backend_test
      - frontend_unit
      - frontend_e2e
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Download Test Results
        uses: actions/download-artifact@v8
        with:
          pattern: test-results-*
          merge-multiple: true
          path: test-results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          files: |
            test-results/**/*.xml
